# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - basestation:

    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/basestation
      - rm -rf ~/deploy_ws/build/basestation
      - rm -rf ~/deploy_ws/install/basestation
      - rm -rf ~/deploy_ws/logs/basestation

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set basestation
        - catkin config
        - catkin build --force-cmake

      - basestation:
        - cd ~/deploy_ws/src/basestation
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set basestation
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set basestation
        - catkin config
        - catkin build --force-cmake
