# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////
  - docker context use default
  
  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - docker-compose-wrapper $scenario build --force-rm ros-cpu-image
    - docker-compose-wrapper $scenario build --force-rm basestation-cpu-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    - shell:
      # - docker-compose-wrapper $scenario -p basestation-shell up --force-recreate -d basestation-shell
      - docker-compose-wrapper $scenario -p basestation-cpu-shell up --force-recreate -d basestation-cpu-shell
    # stopping containers
    - stop:
      - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - docker rm -f $(docker ps -a -q)

