# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # push images to the local docker registry
    - pull:
      # push the docker images to the local registry
      - docker pull $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker pull $AZURE_REGISTRY/subt-basestation-cpu-0.1
      - docker pull $AZURE_REGISTRY/subt-basestation-gpu-ros
      - docker pull $AZURE_REGISTRY/subt-basestation-gpu-0.1
      # tag the docker images
      - docker tag $AZURE_REGISTRY/subt-basestation-cpu-ros subt/basestation-cpu:ros
      - docker tag $AZURE_REGISTRY/subt-basestation-cpu-0.1 subt/basestation-cpu:0.1
      - docker tag $AZURE_REGISTRY/subt-basestation-gpu-ros subt/basestation-gpu:ros
      - docker tag $AZURE_REGISTRY/subt-basestation-gpu-0.1 subt/basestation-gpu:0.1
      # remove the azure docker images
      - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
