# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - uav:
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/uav
      - rm -rf ~/deploy_ws/build/uav
      - rm -rf ~/deploy_ws/install/uav
      - rm -rf ~/deploy_ws/logs/uav
      - rm -rf ~/deploy_ws/src/uav/core/Firmware/build

    # ////////////////////////////////////////////////////////////////////////////
    - px4_firmware:
    # ////////////////////////////////////////////////////////////////////////////
      - cd ~/deploy_ws/src/uav/core/Firmware
      - DONT_RUN=1 make px4_sitl_default gazebo

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - uav:
        - cd ~/deploy_ws/src/uav
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - darpa:
        - cd ~/deploy_ws/src/simulation/darpa/catkin
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - simulation:
        - cd ~/deploy_ws/src/simulation
        # TEMPORARY!
        - touch velodyne_simulator/velodyne_gazebo_plugins/CATKIN_IGNORE
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-simulation
        - catkin config
        - catkin build --force-cmake