# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - docker-compose-wrapper $scenario build --force-rm ros-$deploy_system_type-image
    - docker-compose-wrapper $scenario build --force-rm uav-$deploy_system_type-image
    - docker-compose-wrapper $scenario build --force-rm ros-perception-$deploy_system_type-image
    # tag the image TODO: remove this hack
    - docker tag subt/uav-$deploy_system_type:ros-perception subt/perception-$deploy_system_type:ros
    - docker-compose-wrapper $scenario build --force-rm uav-perception-$deploy_system_type-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    # starting docker containers
    - shell:
      - core:
        # - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d ros-$deploy_system_type-shell
        - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d uav-$deploy_system_type-shell
      - perception:
        - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d uav-perception-$deploy_system_type-shell
      - super:
        - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d uav-superodometry-$deploy_system_type-shell
    # stopping containers
    - stop:
      - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - docker rm -f $(docker ps -a -q)
