# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - docker-compose-wrapper $scenario build --force-rm ros-image
    # temporary for now, move to 'simulation' docker image
    - docker-compose-wrapper $scenario build --force-rm uav-sim-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    - shell:
      - docker-compose-wrapper $scenario -p uav-sim-shell up --force-recreate -d uav-sim-shell
    # == creating docker access containers ==
    # stopping containers
    - stop:
      - all:
        - docker stop $(docker ps -a -q)
      - sim:
        - docker stop uav-sim-shell
    # removing containers
    - rm:
      - all:
        - docker rm $(docker ps -a -q)
      - sim:
        - docker rm uav-sim-shell

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

