- base:
  - basestation:
    - git submodule update --init basestation

  - common:
    - git submodule update --init common

  - operations:
    - docker:
      - git submodule update --init operations/deploy/docker

  - perception:
    - git submodule update --init perception

  - subt_launch:
    - git submodule update --init subt_launch

