blacklist: []
build_space: ../../build/perception/objdet
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
- -DPYTHON_EXECUTABLE=/usr/bin/python3.6
- -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m
- -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
- -DOVERRIDE_DEFAULT_NVCC_FLAGS=ON -DCUDA_NVCC_FLAGS="-O3;-gencode arch=compute_50,code=sm_50"
- -DCMAKE_CXX_COMPILER=g++-7
devel_layout: linked
devel_space: ../../devel/perception/objdet
extend_path: ../../install/perception/objdet_deps
install: false
install_space: ../../install/perception/objdet
isolate_install: false
jobs_args: []
log_space: ../../logs
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
