####################################################################################################
# robot 2 configuration file
- r2:
####################################################################################################

  ##################################################################################################
  - planning-pc:
  ##################################################################################################
    - 'export YELLOW="\033[1;33m"'
    - 'export BLUE="\033[1;36m"'
    - 'export RESET="\033[0m"'

    ################################################################################################
    # copy deploy repo from basestation to r1.planning-pc
    - transfer:
    ################################################################################################
      
      ### == user can modify ==
      # testing setp

      # connections
      - 'export host=ugv2'
      - 'export user=ugv2'
  
      # paths
      - 'export LOCAL_DEPLOY_PATH=/home/$USER/subt/deploy_ws/src'
      - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/'
      
      # rsync options
      - 'export copy_opts="-avzh --exclude=src/perception --exclude=src/state_estimation -e \"ssh -i $HOME/.ssh/deploy\" " ' 
      # rsync commands
      - export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH $user@$host:$REMOTE_DEPLOY_PATH "
      - export copy_from="rsync $copy_opts $user@$host:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH "

      ### == user can modify done. ==

      ####################################################
      # perform actual transfer. do not change.
      ####################################################
      - print:
        # print
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
        - echo -e "\n${YELLOW}\t transfer to -> \t $copy_to \n" ;

      - transfer:
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;

        # transfer TO remote host
        - to:
          # create the remote directory
          - ssh $user@$host -i ~/.ssh/deploy "mkdir -p $REMOTE_DEPLOY_PATH"

          # copy command
          - 'export copy_cmd=$copy_to'

        # transfer FROM remote host
        - from:
          - 'export copy_cmd=$copy_from'

        # evaluate copy
        - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
        - eval $copy_cmd
      
      # delete remote deploy workspace
      - delete:
        - ssh $user@$host "rm -rf $REMOTE_DEPLOY_PATH"

    ################################################################################################
    - docker:
    ################################################################################################
      - +ssh:{ ugv2:ugv2:/home/mtatum/.ssh/deploy }

      ####################################################
      # setup
      ####################################################
      - hostname
      - whoami
      - pwd
      
      ####################################################
      # path setup
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src/'
      - 'export DOCKER_CONFIG=field/r1/planning-pc'
      - 'export DOCKER_CONFIG_PATH=docker/env'
      
      ####################################################
      # print docker configuration information
      ####################################################
      - print:
        - echo -e "\n${BLUE} == Docker images to create == \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/osrf.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/field/r1/planning-pc.config \n" ;
        - echo -e "\n${YELLOW} ** Remember to always transfer any changed configuration files! ** \n";
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG \n" ;
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG_PATH/subt/subt.config \n" ;
        - echo -e "\n${YELLOW}\t subt remote env filepath -> \t $DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config \n"
        - while IFS= read line;
          do 
            echo -e ${BLUE} "\t$line";
          done < "$DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config"

      ####################################################
      # build docker images
      ####################################################
      - cd $DEPLOY_SRC/docker/scripts
      - image:
        - 'export BUILD_ARGS="--force" '
        - osrf:
          - echo $LANG
          - ./build.bash --env local/osrf/ros $BUILD_ARGS
          - ./build.bash --env local/osrf/osrf $BUILD_ARGS
        - subt:
          - ./build.bash --env local/subt/ros $BUILD_ARGS
          - ./build.bash --env field/r1/planning-pc $BUILD_ARGS

      ####################################################
      # start docker images
      ####################################################
      - start:
        - 'export START_ARGS=" --no-nvidia " '
        - ./run.bash --env field/r1/planning-pc $START_ARGS

      ####################################################
      # stop docker images
      ####################################################
      - stop:
        - 'export STOP_ARGS="--stop --containers " '
        - ./clean.bash --env field/r1/planning-pc $STOP_ARGS
      
      - remove:
        - 'export STOP_ARGS="--remove --containers " '
        - ./clean.bash --env field/r1/planning-pc $STOP_ARGS
      
      ####################################################
      # delete docker images & corresponding containers
      ####################################################
      - delete:
        - 'export DELETE_ARGS="--containers" '
        - ./clean.bash --env field/r1/planning-pc $DELETE_ARGS
        - ./clean.bash --env local/subt/ros $DELETE_ARGS
        - ./clean.bash --env local/osrf/osrf $DELETE_ARGS
        - ./clean.bash --env local/osrf/ros $DELETE_ARGS
      
      ####################################################
      # misc.
      ####################################################
      - dangling:
        - docker rmi -f $(docker images -f "dangling=true" -q)
      
    ################################################################################################
    - deploy:
    ################################################################################################
      - +ssh:{ ugv2:ugv2:/home/mtatum/.ssh/deploy }
      - +docker:subt
      
      - hostname
      - whoami
      - pwd
      - 'export DEPLOY_SRC=/home/developer/deploy_ws/src'
      - 'export DEPLOY_WS=/home/developer/deploy_ws/'
      - cd $DEPLOY_SRC
  
      ####################################################
      # clone workspaces
      ####################################################
      - clone:

        # download the subt_robot_examples_latest
        # NOTE: only do this on ONCE. requires internet access.
        - download:
          - if [ -f subt_robot_examples_latest.tgz ]; then
              rm subt_robot_examples_latest.tgz;
            fi
          - wget --no-check-certificate https://s3.amazonaws.com/osrf-distributions/subt_robot_examples/releases/subt_robot_examples_latest.tgz

        # clone & update the planning workspace
        - cd planning/
        
        # setup the rosinstalls
        - rosinstall:
          - planning:
            - darpa:
              - cd darpa/catkin
              - if [ -f .rosinstall ]; then
                  rm .rosinstall;
                fi
              - ln -s $DEPLOY_SRC/rosinstall/planning/darpa.rosinstall .rosinstall
            - thirdparty:
              - cd thirdparty/catkin
              - if [ -f .rosinstall ]; then
                  rm .rosinstall;
                fi
              - ln -s $DEPLOY_SRC/rosinstall/planning/thirdparty.rosinstall .rosinstall
            - repo:
              - if [ -f .rosinstall ]; then
                  rm .rosinstall;
                fi
              - ln -s $DEPLOY_SRC/rosinstall/planning/planning.rosinstall .rosinstall
            - hardware:
              - cd hardware/catkin
              - if [ -f .rosinstall ]; then
                  rm .rosinstall;
                fi
              - ln -s $DEPLOY_SRC/rosinstall/planning/hardware.rosinstall .rosinstall

        # wstool update the workspaces
        - up:
          - planning:
            - darpa:
              - cd darpa/catkin
              - wstool info
              - wstool update
            - thirdparty:
              - cd thirdparty/catkin
              - wstool info
              - wstool update
            - repo:
              - wstool info
              - wstool update
            - hardware:
              - cd hardware/catkin
              - wstool info
              - wstool update

      ####################################################
      # rosdep
      # -- assumes the extended ws are already built
      # -- add only those repos that need rosdep
      ####################################################
      - rosdep:
        # install any thirdparty deps
        - cd planning
        - planning:
          - ./Planning_workspace/install_dependencies.sh

      ####################################################
      # build workspaces
      ####################################################
      - build:
        - planning:
          - cd planning/

          # build the darpa workspaces
          - darpa:
            - cd darpa/catkin
            - catkin build --force-cmake
          
          # install the robot_examples
          - robot_examples:
            - cd $DEPLOY_WS/install/planning/
            - cp $DEPLOY_SRC/subt_robot_examples_latest.tgz .
            - tar xfv subt_robot_examples_latest.tgz -C darpa --strip-components 1

          # build the hardware workspace
          - thirdparty:
            - cd thirdparty/catkin
            - catkin build --force-cmake

          # build planning workspace
          - repo:
            - catkin build --force-cmake

          # build the hardware workspace
          - hardware:
            - cd hardware/catkin
            - catkin build --force-cmake

          # build launch workspace
          - launch:
            - cd $DEPLOY_SRC/launch/
            - catkin profile set planning
            - catkin clean -b --yes
            - catkin build --force-cmake

      ####################################################
      # clean workspaces
      ####################################################
      - clean:
        - launch:
          - cd $DEPLOY_SRC/launch/
          - catkin clean -y
        - planning:
          - cd $DEPLOY_SRC/planning/
          - hardware:
            - cd hardware/catkin
            - catkin clean -y
          - repo:
            - catkin clean -y
          - thirdparty:
            - cd thirdparty/catkin
            - catkin clean -y
          - darpa:
            - cd darpa/catkin
            - catkin clean -y

      ####################################################
      # remove workspaces
      ####################################################
      - rm:
        - planning:
          - cd planning/
          - repo:
            - find . -maxdepth 1 \! \( -name darpa -o -name thirdparty -o -name hardware -o -name .catkin_tools \) -exec rm -rf '{}' \;
          - hardware:
            - cd hardware/catkin
            - find . -maxdepth 1 \! \( -name .catkin_tools \) -exec rm -rf '{}' \;
          - darpa:
            - cd darpa/catkin
            - find . -maxdepth 1 \! \( -name .catkin_tools \) -exec rm -rf '{}' \;
          - thirdparty:
            - cd thirdparty/catkin
            - find . -maxdepth 1 \! \( -name .catkin_tools \) -exec rm -rf '{}' \;

      ####################################################
      # launch workspaces
      ####################################################
      - launch:
        ### == user can modify ==
        
        # launch configuration variables
        - 'export host=$(hostname)'
        - 'export config=robots/r2/planning-pc'
        - 'export MCAST_GROUP=224.0.0.251'
        - 'export robot=robots/planning-pc'
        - 'export USER=ugv2'
        - 'export ROS_MASTER_URI=http://ugv2:11311'
        - 'export ROS_HOSTNAME=ugv2'

        ### == user can modify done. ==

        # read the launch configuration params
        - export config_data=""
        - export CONFIG_FILE="$DEPLOY_SRC/launch/robot_launch_scripting/config/${config}.config"
        - while IFS='' read -r line || [[ -n "$line" ]]; do
            if [ ! "${line:0:1}" == "#" ]; then
              config_data="$line ";
            fi
          done < "$CONFIG_FILE";
        - echo ${config_data}

        - start:
          - roscore:
            # enable roscore
            - 'export ROS_MASTER=true'
            # start the tmux sessions
            - tmux new -s ${host}_roscore -d
            # source
            - tmux send -t ${host}_roscore 'source $DEPLOY_WS/devel/planning/launch/setup.bash' ENTER
            # run roscore
            - tmux send -t ${host}_roscore 'rosrun robot_launch_scripting launch_roscore.sh' ENTER
          - planning:
            # start the tmux session
            - tmux new -s ${host}_launch_planning -d
            # source
            - tmux send -t ${host}_launch_planning 'source $DEPLOY_WS/devel/planning/launch/setup.bash' ENTER
            # run autonomy launch
            - tmux send -t ${host}_launch_planning 'mon launch robot_launch_scripting subt.launch robot:=$robot autonomy:=true fkie:=true' ENTER
            # message user
            - echo "Launch deployed in tmux session ${host}_launch_planning"
          - hardware:
            # start the tmux session
            - tmux new -s ${host}_launch_hardware -d
            # source
            - tmux send -t ${host}_launch_hardware 'source $DEPLOY_WS/devel/planning/launch/setup.bash' ENTER
            # run hardware launch
            - tmux send -t ${host}_launch_hardware 'mon launch robot_launch_scripting subt.launch robot:=$robot teleop:=true' ENTER
            # message user
            - echo "Launch deployed in tmux session ${host}_launch_${config}"
          # TODO: remove & add as command line suffix to tmux name...
          - shell:
            - pwd
            - tmux new -s ${host}_shell -d
            - tmux send -t ${host}_shell 'source $DEPLOY_WS/devel/launch/setup.bash' ENTER

        - stop:
          # remove all the tmux sessions
          - roscore:
            - tmux kill-session -t ${host}_roscore
          - planning:
            - tmux kill-session -t ${host}_launch_planning
          - hardware:
            - tmux kill-session -t ${host}_launch_hardware
          - shell:
            - tmux kill-session -t ${host}_shell
          
        - rosclean:
          # stop all ros nodes
          - source $DEPLOY_WS/devel/planning/repo/setup.bash
          - ps aux | grep ros
          - rosnode kill -a
          - pkill -f ros
          - rosnode list
          - ps aux | grep ros
        
        # change sizes depending on host screen size.
        - view:
          - export TERM="xterm-256color"
          - stty size
          # - stty rows 60 cols 150
          - stty rows 30 cols 150
          - tmux a -t ${host}_launch_${config}

      ####################################################
      # git updater
      ####################################################
      - git:
        - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
        - 'export DEPLOY_SRC=$DEPLOY_WS/src'
        
        # git status check          
        - git_status() {
            for repo in $1; do
              pushd $repo  > /dev/null 2>&1;
              if [ -d .git ]; then
                echo -e "\n${YELLOW}\trepo -> \t $(basename $repo) \n ${RESET}" ;
                git config --get remote.origin.url;
                git status;
                echo -e "\n\n";
              fi;
              popd  > /dev/null 2>&1;
            done;
          }
        - export -f git_status

        # git status check          
        - git_dirty() {
            for repo in $1; do
              pushd $repo  > /dev/null 2>&1;
              if [ -d .git ]; then
                if [[ $(git status -s) ]]; then
                  echo -e "\n${YELLOW}\trepo -> \t $(basename $repo) \n ${RESET}" ;
                  git config --get remote.origin.url;
                  git status;
                  echo -e "\n\n";
                fi;
              fi;
              popd  > /dev/null 2>&1;
            done;
          }
        - export -f git_dirty

        # wstool update to git hash
        - git_updater() {
            for repo in $1; do
              echo "repo is $repo";
              pushd $repo  > /dev/null 2>&1;
              if [ -d .git ]; then
                echo -e "\n${YELLOW}\trepo -> \t $(basename $repo) \n ${RESET}" ;
                export GIT_COMMIT_HASH=$(git rev-parse --verify HEAD);
                export ROSINSTALL_GIT_HASH=$(wstool info $(basename $repo) --yaml | grep -oP "version\K.*" | grep -oP " \K.*");
                wstool set $(basename $repo) -v $GIT_COMMIT_HASH -y;
                echo -e "\n\n";
              fi;
              popd  > /dev/null 2>&1;
            done;
          }
        - export -f git_updater

        ####################################################
        # git commands for planning workspace
        ####################################################
        - planning:
          - cd $DEPLOY_SRC/planning

          # git update to darpa ws
          - darpa:
            - status:
              - 'export git_fn=git_status'
            - update:
              - 'export git_fn=git_updater'
            - dirty:
              - 'export git_fn=git_dirty'
            # execute git fn
            - cd darpa/catkin
            - export REPOS=$(find . -maxdepth 1 \! \( -name .catkin_tools -o -name .rosinstall \) )
            - $git_fn "$REPOS"

          # git update to thirdparty ws
          - thirdparty:
            - status:
              - 'export git_fn=git_status'
            - update:
              - 'export git_fn=git_updater'
            - dirty:
              - 'export git_fn=git_dirty'
            # execute git fn            
            - cd thirdparty/catkin
            - export REPOS=$(find . -maxdepth 1 \! \( -name .catkin_tools -o -name .rosinstall \) )
            - $git_fn "$REPOS"

          # git update to repo ws
          - repo:
            - status:
              - 'export git_fn=git_status'
            - update:
              - 'export git_fn=git_updater'
            - dirty:
              - 'export git_fn=git_dirty'
            # execute git fn
            - export REPOS=$(find . -maxdepth 1 \! \( -name darpa -o -name thirdparty -o -name hardware -o -name .catkin_tools -o -name .rosinstall \) )
            - $git_fn "$REPOS"


