blacklist: []
build_space: ../../build/uav/inside/common/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/uav/inside/common
extend_path: /opt/ros/melodic
install: false
install_space: ../../install/uav/inside/common/
isolate_install: false
jobs_args: []
log_space: ../../logs/uav/inside/common/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
