blacklist:
- xsens_cpp_driver
- xsense_driver
- receive_xsens
build_space: ../../build/ugv/ppc/core
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/ugv/ppc/core
extend_path: /home/developer/deploy_ws/devel/ugv/ppc/common
install: false
install_space: ../../install/ugv/ppc/core
isolate_install: false
jobs_args: []
log_space: ../../logs/ugv/ppc/core
make_args: []
source_space: planning-pc
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
