# //////////////////////////////////////////////////////////////////////////
# local system basestation docker images
# //////////////////////////////////////////////////////////////////////////

# extend compose image build
- +extend: subt/basestation/compose/basestation

