blacklist: []
build_space: ../../build/perception/common/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
- -DPYTHON_EXECUTABLE=/usr/bin/python3.6
- -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m
- -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so
devel_layout: linked
devel_space: ../../devel/perception/common/
extend_path: /opt/ros/melodic
install: false
install_space: ../../install/perception/common/
isolate_install: false
jobs_args: []
log_space: ../../logs/perception/common/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist:
- base
- base_py
- objdet_msgs
- basestation_msgs
- rosmon
- rosmon_core
- rosmon_msgs
- rqt_rosmon
- object_ledger
- map_database
- map_database_msgs
