---
# ////////////////////////////////////////////////////////////////////////
# install & setup gnome desktop
# ////////////////////////////////////////////////////////////////////////
- name: Gnome Desktop Setup

  # setup variables to be shared in tasks
  vars_files:
    - ../vars/main.yaml

  # setup hosts to run commands as
  hosts:
    - localhost
    - basestation
    - ugv
    - uav
    - perception
  become_method: sudo
  become_user: root

  # ////////////////////////////////////////////////////////////////////////
  # Tasks to execute
  # ////////////////////////////////////////////////////////////////////////
  tasks:

    # ////////////////////////////////////////////////////////////////////////
    # Install GNOME Desktop
    # ////////////////////////////////////////////////////////////////////////
    - name: update apt packages
      become: true
      apt:
        force: yes          # force yes
        force_apt_get: yes
        install_recommends: yes
        update_cache: yes   # force apt-get update

    - name: install GNOME vanilla
      become: true
      apt:
        name: "{{ gnome_vanilla_packages }}"
        state: present
        force: yes          # force yes
        force_apt_get: yes
        install_recommends: yes
        update_cache: yes   # force apt-get update

    - name: install GNOME prerequisite
      become: true
      apt:
        name: "{{ gnome_prerequisite_packages }}"
        state: present
        force: yes          # force yes
        force_apt_get: yes
        install_recommends: yes
        update_cache: yes   # force apt-get update

    - name: install GNOME desktop
      become: true
      apt:
        name: "{{ gnome_desktop_packages }}"
        state: present
        force: yes          # force yes
        force_apt_get: yes
        install_recommends: yes
        update_cache: yes   # force apt-get update

    - name: tasksel install GNOME Desktop
      become: true
      shell:
        cmd: tasksel install ubuntu-desktop
      ignore_errors: True

    - name: enable service gdm3
      become: true
      systemd:
        name: gdm3
        state: started  # make sure service is running
        enabled: yes    # start service on boot
        masked: no

    - name: restart service gdm3
      become: true
      systemd:
        name: gdm3
        state: restarted  # make sure service is running
        enabled: yes      # start service on boot
        masked: no

    - name: remove previous dummy Xorg
      become: true
      file:
        path: /usr/share/X11/xorg.conf.d/xorg.conf
        state: absent

    - name: add dummy Xorg
      become: true
      copy:
        src: dummy-xorg.conf
        dest: '/usr/share/X11/xorg.conf.d/xorg.conf'

    - name: reboot machine
      become: true
      reboot:
        reboot_timeout: 3600
