blacklist: []
build_space: ../../build/wifi/core
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/wifi/core
extend_path: /home/katarina/deploy_ws/devel/wifi/common
install: false
install_space: ../../install/wifi/core
isolate_install: false
jobs_args: []
log_space: ../../logs/wifi/core
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist:
- bluetooth_detection
