# //////////////////////////////////////////////////////////////////////////////
- local:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/local/.local.env

  # ////////////////////////////////////////////////////////////////////////////
  - uav.cpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/local/uav-cpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - compose:
      - +extend: systems/local/uav/vm/compose
    - catkin:
      # - +docker:uav-cpu-shell
      - +extend: systems/local/uav/vm/catkin


  # ////////////////////////////////////////////////////////////////////////////
  - uav.gpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/local/uav-gpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - compose:
      - +extend: systems/local/uav/vm/compose
    - catkin:
      # - +docker:uav-gpu-shell
      - +extend: systems/local/uav/vm/catkin

