# //////////////////////////////////////////////////////////////////////////////
- local:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/local/.local.env


  # ////////////////////////////////////////////////////////////////////////////
  - uav.cpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/local/uav-cpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - registry:
      - +extend: systems/local/uav/vm/registry
    - compose:
      - +extend: systems/local/uav/vm/compose
    - catkin:
      - core:
        - +docker:uav-superodometry-shell
        - +extend: systems/local/uav/vm/catkin-core
      - perception:
        - +docker:uav-perception-cpu-shell
        - +extend: systems/local/uav/vm/catkin-perception


  # ////////////////////////////////////////////////////////////////////////////
  - uav.gpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/local/uav-gpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - registry:
      - +extend: systems/local/uav/vm/registry
    - compose:
      - +extend: systems/local/uav/vm/compose
    - catkin:
      - core:
        - +docker:uav-gpu-shell
        - +extend: systems/local/uav/vm/catkin-core
      - perception:
        - +docker:uav-perception-gpu-shell
        - +extend: systems/local/uav/vm/catkin-perception

