blacklist: []
build_space: ../../build/state_estimation/launch
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/state_estimation/launch
extend_path: ../../devel/state_estimation/repo
install: false
install_space: ../../install/state_estimation/launch
isolate_install: false
jobs_args: []
log_space: ../../logs/state_estimation/launch
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
