# add '--force-rm '
- image:
  - docker-compose-wrapper $scenario build ros-image
  - docker-compose-wrapper $scenario build gui-image
  # any compose command -- user can add '-e arg="launch build-gui"' to specify command
- container:
  - docker-compose-wrapper $scenario -p ${deploybook_run}-start up --force-recreate -d gui-commander-run
- run-any:
  - docker-compose-wrapper $scenario -p ${deploybook_run}-run up --force-recreate -d gui-commander-run-any
- shell:
  # - docker-compose-wrapper $scenario up --force-recreate -d ros-shell
  - docker-compose-wrapper $scenario -p basestation-shell up --force-recreate -d gui-shell

