# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # == creating docker images ==
  - image:
    - docker-compose-wrapper $scenario build --force-rm ros-cpu-image
    - docker-compose-wrapper $scenario build --force-rm basestation-cpu-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # == creating docker access containers ==
  - shell:
    # - docker-compose-wrapper $scenario -p basestation-shell up --force-recreate -d basestation-shell
    - docker-compose-wrapper $scenario -p basestation-cpu-shell up --force-recreate -d basestation-cpu-shell

  # == creating docker run containers ==
  - container.run:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-start up --force-recreate -d basestation-commander-run
  # any compose command -- user can add '-e arg="launch build-gui"' to specify command
  - container.exec:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-run up --force-recreate -d basestation-commander-run-any
