# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # push images to the local docker registry
    - push:
      # tag the docker images
      - docker tag subt/basestation-cpu:ros $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker tag subt/basestation-cpu:0.1 $AZURE_REGISTRY/subt-basestation-cpu-0.1
      # push the docker images to the local registry
      - docker push $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker push $AZURE_REGISTRY/subt-basestation-cpu-0.1
      # remove the azure docker images
      - docker rmi $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker rmi $AZURE_REGISTRY/subt-basestation-cpu-0.1

    # pull images from the docker registry
    - pull:
      # pull the docker images from the laptop local registry
      - docker pull $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker pull $AZURE_REGISTRY/subt-basestation-cpu-0.1
      # tag the docker images
      - docker tag $AZURE_REGISTRY/subt-basestation-cpu-ros subt/basestation-cpu:ros
      - docker tag $AZURE_REGISTRY/subt-basestation-cpu-0.1 subt/basestation-cpu:0.1
      # remove the azure docker images
      - docker rmi $AZURE_REGISTRY/subt-basestation-cpu-ros
      - docker rmi $AZURE_REGISTRY/subt-basestation-cpu-0.1
