- basestation:
  - git submodule update --recursive --init basestation
  - cd basestation
  - git clean -d -f -f

- common:
  - git submodule update --recursive --init common
  - cd common
  - git clean -d -f -f
  # ignore the catkin profiles
  - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
  # git lfs steps
  - cd communication_manager
  - git lfs fetch
  - git lfs pull
  - git lfs install

- operations:
  - docker:
    - git submodule update --recursive --init operations/deploy/docker
    - cd operations/deploy/docker
    - git clean -d -f -f

- perception:
  - git submodule update --recursive --init perception
  - cd perception
  - git clean -d -f -f
  # ignore the catkin profiles
  - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
  - cd object_detection
  - git clean -d -f -f

- subt_launch:
  - git submodule update --recursive --init subt_launch
  - cd subt_launch
  - git clean -d -f -f
  # ignore the catkin profiles
  - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml

