- simulation:
  - git submodule update --recursive --init simulation
  - cd simulation
  - git clean -d -f -f
  # ignore the catkin profiles
  - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --assume-unchanged darpa/catkin/.catkin_tools/profiles/profiles.yaml
  # git lfs steps
  - cd subt_gazebo
  - git lfs fetch
  - git lfs pull
  - git lfs install