blacklist:
- behavior_tree_blink_monitor
- blink1
- bluetooth_detection
- scd30_ros
- teraranger
- deca_ros_driver
- receive_xsens
build_space: ../../build/uav/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/uav/
extend_path: ../../devel/uav/common
install: false
install_space: ../../install/uav/
isolate_install: false
jobs_args: []
log_space: ../../logs/uav/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
