# //////////////////////////////////////////////////////////////////////////////
- robots:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/robot/.robot.env

  # ////////////////////////////////////////////////////////////////////////////
  - ugv1:
  # ////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    # tasks (transfer, compose, catkin) tasks for computers: ppc, nuc, xavier
    # //////////////////////////////////////////////////////////////////////////
    - ppc:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv1-ppc
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv1.ppc }
        - +extend: systems/robot/ugv/ppc/compose
      - catkin:
        - +ssh:{ ugv1.ppc }
        - +docker:ppc-shell
        - +extend: systems/robot/ugv/ppc/catkin

    - nuc:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv1-nuc
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv1.nuc }
        - +extend: systems/robot/ugv/nuc/compose
      - catkin:
        - +ssh:{ ugv1.nuc }
        - +docker:nuc-shell
        - +extend: systems/robot/ugv/nuc/catkin

    - xavier:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv1-xavier
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv1.xavier }
        - +extend: systems/robot/ugv/xavier/compose

  # ////////////////////////////////////////////////////////////////////////////
  - ugv2:
  # ////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    # tasks (transfer, compose, catkin) tasks for computers: ppc, nuc, xavier
    # //////////////////////////////////////////////////////////////////////////
    - ppc:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv2-ppc
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv2.ppc }
        - +extend: systems/robot/ugv/ppc/compose
      - catkin:
        - +ssh:{ ugv2.ppc }
        - +docker:ppc-shell
        - +extend: systems/robot/ugv/ppc/catkin

    - nuc:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv2-nuc
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv2.nuc }
        - +extend: systems/robot/ugv/nuc/compose
      - catkin:
        - +ssh:{ ugv2.nuc }
        - +docker:nuc-shell
        - +extend: systems/robot/ugv/nuc/catkin

    - xavier:
      # source the computer-level scenario file
      - export filename=systems/robot/ugv2-xavier
      - source operations/deploy/scenarios/$filename.env
      - 'export scenario=" --scenario $filename"'

      # extend
      - +extend: common/transfer
      - compose:
        - +ssh:{ ugv2.xavier }
        - +extend: systems/robot/ugv/xavier/compose
