# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - uav:
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/uav
      - rm -rf ~/deploy_ws/build/uav
      - rm -rf ~/deploy_ws/install/uav
      - rm -rf ~/deploy_ws/logs/uav
      - rm -rf ~/deploy_ws/src/uav/core/firmwaresubt/build

    # ////////////////////////////////////////////////////////////////////////////
    - px4:
    # ////////////////////////////////////////////////////////////////////////////
      - cd ~/deploy_ws/src/uav/core/firmwaresubt
      - ./build.sh

    # //////////////////////////////////////////////////////////////////////////
    - xsens:
    # //////////////////////////////////////////////////////////////////////////
      - cd ~/deploy_ws/src/uav/hardware/xsens_cpp_driver/receive_xsens/config/mt_sdk/
      - sudo ./mt_sdk_4.8.sh

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - uav:
        - cd ~/deploy_ws/src/uav
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-sim
        - catkin config
        - catkin build --force-cmake

      - darpa:
        - cd ~/deploy_ws/src/simulation/darpa/catkin
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - simulation:
        - cd ~/deploy_ws/src/simulation
        # TEMPORARY!
        - touch velodyne_simulator/velodyne_gazebo_plugins/CATKIN_IGNORE
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-sim
        - catkin config
        - catkin build --force-cmake