# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////
    # use default docker context
    - docker context use default

    - push:
      # tag the images for azure
      - docker tag subt/uav-$deploy_system_type:ros $AZURE_REGISTRY/subt-uav-$deploy_system_type-ros
      - docker tag subt/uav-$deploy_system_type:uav $AZURE_REGISTRY/subt-uav-$deploy_system_type-uav
      - docker tag subt/uav-$deploy_system_type:superodometry $AZURE_REGISTRY/subt-uav-$deploy_system_type-superodometry
      # push the docker images to azure registry
      - docker push $AZURE_REGISTRY/subt-uav-$deploy_system_type-ros
      - docker push $AZURE_REGISTRY/subt-uav-$deploy_system_type-uav
      - docker push $AZURE_REGISTRY/subt-uav-$deploy_system_type-superodometry
    - pull:
      # pull from the azure registry
      - docker pull $AZURE_REGISTRY/subt-uav-$deploy_system_type-ros
      - docker pull $AZURE_REGISTRY/subt-uav-$deploy_system_type-uav
      - docker pull $AZURE_REGISTRY/subt-uav-$deploy_system_type-superodometry
      # tag the docker images
      - docker tag $AZURE_REGISTRY/subt-uav-$deploy_system_type-ros subt/uav-$deploy_system_type:ros
      - docker tag $AZURE_REGISTRY/subt-uav-$deploy_system_type-uav subt/uav-$deploy_system_type:uav
      - docker tag $AZURE_REGISTRY/subt-uav-$deploy_system_type-superodometry subt/uav-$deploy_system_type:uav

    # remove the azure docker images
    - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
    # show the docker images
    - docker images
