- ugv:
  - slam:
    - devel:
      - cd slam/devel
      - git submodule update --init --recursive .
      - git clean -d -f -f
    - robot:
      - cd slam/robot
      - git submodule update --init --recursive .
      - git clean -d -f -f
