- basestation:
  - cd basestation
  - git submodule update --recursive --init .
  - git clean -d -f -f

- common:
  - cd common
  - git submodule update --recursive --init .
  - git clean -d -f -f
  # git lfs steps
  - cd communication_manager
  - git lfs fetch
  - git lfs pull
  - git lfs install

- operations:
  - docker:
    - git submodule update --recursive --init operations/deploy/docker
    - cd operations/deploy/docker
    - git clean -d -f -f

- perception:
  - cd perception
  - git submodule update --recursive --init .
  - git clean -d -f -f
  - cd object_detection
  - git submodule update --recursive --init .
  - git clean -d -f -f

- subt_launch:
  - cd subt_launch
  - git submodule update --recursive --init .
  - git clean -d -f -f
