blacklist: []
build_space: ../../build/basestation/repo
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/basestation/repo
extend_path: ../../devel/basestation/thirdparty
install: false
install_space: ../../install/basestation/repo
isolate_install: false
jobs_args: []
log_space: ../../logs/basestation/repo/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
