# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - cd $SUBT_PATH/
  - pwd
  - whoami

  # ////////////////////////////////////////////////////////////////////////////
  - px4:
  # ////////////////////////////////////////////////////////////////////////////
    - build:
      - cd ~/deploy_ws/src/uav/core/firmwaresubt
      - ./build.sh
    - clean:
      - rm -rf ~/deploy_ws/src/uav/core/firmwaresubt/build

  # //////////////////////////////////////////////////////////////////////////
  - uav.core:
  # //////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/uav/inside
      - rm -rf ~/deploy_ws/build/uav/inside
      - rm -rf ~/deploy_ws/install/uav/inside
      - rm -rf ~/deploy_ws/logs/uav/inside

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////
      # - +docker:uav-cpu-shell
      - +docker:uav-superodometry-cpu-shell

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-inside
        - catkin config
        - catkin build --force-cmake

      - uav:
        - cd ~/deploy_ws/src/uav
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-inside
        - catkin config
        - catkin build --force-cmake

      - darpa:
        - cd ~/deploy_ws/src/simulation/darpa/catkin
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - simulation:
        - cd ~/deploy_ws/src/simulation

        # TEMPORARY! REALLY BAD.
        - touch velodyne_simulator/velodyne_gazebo_plugins/CATKIN_IGNORE
        # - touch payload_sim_uav/CATKIN_IGNORE
        # - rm payload_sim_uav/CATKIN_IGNORE
        # - touch payload_sim_ugv/CATKIN_IGNORE

        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-inside
        - catkin config
        - catkin build --force-cmake

  # //////////////////////////////////////////////////////////////////////////
  - uav.perception:
  # //////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/perception
      - rm -rf ~/deploy_ws/build/perception
      - rm -rf ~/deploy_ws/install/perception
      - rm -rf ~/deploy_ws/logs/perception

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////
      - +docker:uav-perception-cpu-shell

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set perception-x86
        - catkin config
        - catkin build --force-cmake

      - perception:
        - deps:
          # build perception deps
          - cd ~/deploy_ws/src/perception/deps/catkin
          - rm -f .catkin_tools/profiles/profiles.yaml
          - catkin profile list
          -  catkin profile set perception-x86
          - catkin config
          - catkin build --force-cmake
        - objdet:
          # build objdet
          - cd ~/deploy_ws/src/perception/
          - rm -f .catkin_tools/profiles/profiles.yaml
          - catkin profile list
          - catkin profile set perception-x86
          - catkin config
          - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set perception-x86
        - catkin config
        - catkin build --force-cmake

  # //////////////////////////////////////////////////////////////////////////
  - uav.wifi:
  # //////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/wifi
      - rm -rf ~/deploy_ws/build/wifi
      - rm -rf ~/deploy_ws/install/wifi
      - rm -rf ~/deploy_ws/logs/wifi

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-wifi
        - catkin config
        - catkin build --force-cmake

      - perception:
        # build objdet
        - cd ~/deploy_ws/src/perception/
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-wifi
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set uav-wifi
        - catkin config
        - catkin build --force-cmake
