# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # == creating docker images ==
  - image:
    - docker-compose-wrapper $scenario build --force-rm ros-$deploy_system_type-image
    - docker-compose-wrapper $scenario build --force-rm uav-$deploy_system_type-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # == creating docker containers ==
  - container:
    # starting docker containers
    - shell:
      # - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d ros-$deploy_system_type-shell
      - docker-compose-wrapper $scenario -p uav-$deploy_system_type-shell up --force-recreate -d uav-$deploy_system_type-shell
    # stopping containers
    - stop:
      - all:
        - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - all:
        - docker rm -f $(docker ps -a -q)

  # == docker registry ==

  # pull images from the docker registry
  - pull:
    # pull the docker images from the laptop local registry
    - docker pull $BASESTATION_REGISTRY:5000/subt-uav-gpu-ros
    - docker pull $BASESTATION_REGISTRY:5000/subt-uav-gpu-uav
    - docker pull $BASESTATION_REGISTRY:5000/subt-uav-cpu-ros
    - docker pull $BASESTATION_REGISTRY:5000/subt-uav-cpu-uav
    # tag the docker images
    - docker tag $BASESTATION_REGISTRY:5000/subt-uav-gpu-ros subt/uav-gpu:ros
    - docker tag $BASESTATION_REGISTRY:5000/subt-uav-gpu-uav subt/uav-gpu:uav
    - docker tag $BASESTATION_REGISTRY:5000/subt-uav-cpu-ros subt/uav-cpu:ros
    - docker tag $BASESTATION_REGISTRY:5000/subt-uav-cpu-uav subt/uav-cpu:uav

