# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/azure/.azure.env

  # ////////////////////////////////////////////////////////////////////////////
  - basestation:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/basestation
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - compose:
        - +ssh:{ azure.basestation }
        - +extend: systems/azure/basestation/vm/compose
      - catkin:
        - +ssh:{ azure.basestation }
        - +docker:basestation-shell
        - +extend: systems/azure/basestation/vm/catkin
