- basestation:
  - cd basestation
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/basestation/config.yaml

- common:
  - cd common
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/basestation/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-arm/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-x86/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-inside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-outside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-wifi/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-nuc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-nuc-perception/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-ppc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-sim/config.yaml

- perception:
  - cd perception
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/nuc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-arm/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-x86/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-wifi/config.yaml
  # ignore all .catkin_profile files in deps
  - cd deps/catkin/
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/nuc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-arm/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-x86/config.yaml

- uav:
  - cd uav
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-inside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-sim/config.yaml

  # ignore non-catkin files
  - cd $SUBT_PATH
  - export filename=".git/modules/uav/modules/core/mavlink/info/exclude"
  - sed -i '/pymavlink/d' $filename
  - export filename=".git/modules/uav/modules/core/rqt_behavior_tree_command/info/exclude"
  - sed -i '/rqt_behavior_tree_command/d' $filename

- ugv:
  - cd ugv
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-nuc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-ppc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-slam/config.yaml

- subt_launch:
  - cd subt_launch
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/basestation/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-arm/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/perception-x86/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-inside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-outside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-wifi/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-loam/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-nuc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-nuc-perception/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-ppc/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv-slam/config.yaml

- simulation:
  - cd simulation
  # ignore all .catkin_profile files
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-inside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv/config.yaml
  - git update-index --no-assume-unchanged payload_sim_uav/CATKIN_IGNORE || true
  - git update-index --no-assume-unchanged payload_sim_ugv/CATKIN_IGNORE || true
  - git update-index --no-assume-unchanged velodyne_simulator/velodyne_gazebo_plugins/CATKIN_IGNORE || true
  - cd darpa/catkin
  - git update-index --no-assume-unchanged .catkin_tools/VERSION
  - git update-index --no-assume-unchanged .catkin_tools/profiles/profiles.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-inside/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/uav-sim/config.yaml
  - git update-index --no-assume-unchanged .catkin_tools/profiles/ugv/config.yaml

  # ignore non-catkin files
  - cd $SUBT_PATH
  - export filename=".git/modules/simulation/modules/payload_sim_ugv/info/exclude"
  - sed -i '/CATKIN_IGNORE/d' $filename
  - export filename=".git/modules/simulation/modules/payload_sim_uav/info/exclude"
  - sed -i '/CATKIN_IGNORE/d' $filename
  - export filename=".git/modules/simulation/modules/velodyne_simulator/info/exclude"
  - sed -i '/CATKIN_IGNORE/d' $filename