blacklist: []
build_space: ../../build/uav/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/uav/
extend_path: /home/developer/deploy_ws/devel/uav/sim
install: false
install_space: ../../install/uav/
isolate_install: false
jobs_args: []
log_space: ../../logs/uav/launch/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
