blacklist: []
build_space: ../../build/uav/launch/
catkin_make_args: []
cmake_args:
- -DCMAKE_SOURCE_PARAMS_PATH=../../devel/uav/launch/
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/uav/launch/
extend_path: ../../devel/uav/sim
install: false
install_space: ../../install/uav/launch/
isolate_install: false
jobs_args: []
log_space: ../../logs/uav/launch/launch/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
