# //////////////////////////////////////////////////////////////////////////
# local system basestation docker images
# //////////////////////////////////////////////////////////////////////////
- docker:
  - image:
    - docker-compose-wrapper $scenario build --force-rm ros-image
    - docker-compose-wrapper $scenario build --force-rm gui-image
    # any compose command -- user can add '-e arg="launch build-gui"' to specify command
  - container:
    - docker-compose-wrapper $scenario -p ${deploybook_run} up -d gui-commander-run
  - shell:
    - docker-compose-wrapper $scenario up --force-recreate -d ros-shell
    - docker-compose-wrapper $scenario up --force-recreate -d gui-shell
