# //////////////////////////////////////////////////////////////////////////
# local system basestation docker images
# //////////////////////////////////////////////////////////////////////////

# extend compose image build
- +extend: robot/basestation/compose/basestation

