#!/usr/bin/env bash

# create & go to the logging directory
date=$(date '+%Y-%m-%d')
mkdir -p $subt_rosbag_dir/$date/
cd $subt_rosbag_dir/$date/

# rosbag record specific topics
rosbag record --split -b 1024 --size 1024 __name:=rosbag_recording_base_station -o base_station \
    /basic_controls/feedback \
    /basic_controls/update \
    /basic_controls/update_full \
    /comm_dropper/complete \
    /comm_dropper/stacks/count \
    /comm_dropper/stacks/select \
    /comm_dropper/start \
    /define_waypoint/feedback \
    /define_waypoint/update \
    /define_waypoint/update_full \
    /define_waypoint_marker_off \
    /define_waypoint_marker_pos \
    /from_gui \
    /gui_message_listener \
    /heartbeat_base_station \
    /heartbeat_uav \
    /move_base_simple/goal \
    /position \
    /real_artifact_detections \
    /real_artifact_imgs \
    /refinement_marker_off \
    /refinement_marker_orig_pos \
    /refinement_marker_pos \
    /ros_to_teensy \
    /rosout_agg \
    /safe_landing_goal \
    /state \
    /status_panel_update \
    /tf \
    /tf_relay \
    /tf_static \
    /tf_static_relay \
    /trajectory_library_vis \
    /trajectory_vis \
    /uav1/heartbeat \
    /uav1/clusters \
    /uav1/decode_cloud_pose \
    /uav1/decode_global_cloud \
    /uav1/decode_local_cloud \
    /uav1/det_centers \
    /uav1/dfs_mode \
    /uav1/dfs_planner_markers \
    /uav1/image_resize_drop_theora/theora \
    /uav1/integrated_to_map \
    /uav1/mavros/local_position/odom \
    /uav1/node_monitor/err_msg \
    /uav1/pause \
    /uav1/real_artifact_detections \
    /uav1/real_artifact_imgs \
    /uav1/return_home \
    /uav1/cloud_clearing \
    /uav1/complete_cloud \
    /uav1/coordination_polygon \
    /uav1/radio_command_bst \
    /uav1/transform \
    /uav1/way_point \
    /ugv1/autonomy_mode \
    /ugv1/clusters \
    /ugv1/decode_cloud_pose \
    /ugv1/decode_global_cloud \
    /ugv1/decode_local_cloud \
    /ugv1/det_centers \
    /ugv1/dfs_mode \
    /ugv1/dfs_planner_markers \
    /ugv1/image_resize_drop_theora/theora \
    /ugv1/integrated_to_map \
    /ugv1/motor_status \
    /ugv1/node_monitor/err_msg \
    /ugv1/pause \
    /ugv1/real_artifact_detections \
    /ugv1/real_artifact_imgs \
    /ugv1/return_home \
    /ugv1/cloud_clearing \
    /ugv1/complete_cloud \
    /ugv1/coordination_polygon \
    /ugv1/radio_command_bst \
    /ugv1/transform \
    /ugv1/way_point \
    /xbee_ugv1_odom \
    /ugv2/autonomy_mode \
    /ugv2/clusters \
    /ugv2/decode_cloud_pose \
    /ugv2/decode_global_cloud \
    /ugv2/decode_local_cloud \
    /ugv2/det_centers \
    /ugv2/dfs_mode \
    /ugv2/dfs_planner_markers \
    /ugv2/image_resize_drop_theora/theora \
    /ugv2/integrated_to_map \
    /ugv2/motor_status \
    /ugv2/node_monitor/err_msg \
    /ugv2/pause \
    /ugv2/real_artifact_detections \
    /ugv2/real_artifact_imgs \
    /ugv2/return_home \
    /ugv2/cloud_clearing \
    /ugv2/complete_cloud \
    /ugv2/coordination_polygon \
    /ugv2/radio_command_bst \
    /ugv2/transform \
    /ugv2/way_point \
    /xbee_ugv2_odom \
    /MasterDiscovery/changes \
    /MasterDiscovery/linkstats \
    /bst_twist \
    /comms_monitor_heartbeat \
    /comms_status \
    /diagnostics_agg \
    /joy \
