# //////////////////////////////////////////////////////////////////////////////
- desktop:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario desktop-perception"'
  # source the scenario file
  - source operations/deploy/scenarios/desktop-perception.env

  # perception
  - export deploybook_robot=desktop.perception
  - +extend: robot/perception/compose/perception

# //////////////////////////////////////////////////////////////////////////////
- system76-pc:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario system76-pc-perception"'
  # source the scenario file
  - source operations/deploy/scenarios/system76-pc-perception.env  

  # perception
  - export deploybook_robot=system76-pc.perception
  - +extend: robot/perception/compose/perception

# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the base scenario file
  - source operations/deploy/scenarios/azure/.azure.env

  # scenario file
  - 'export scenario=" --scenario azure/perception"'
  # source the scenario file
  - source operations/deploy/scenarios/azure/perception.env  

  # extend all the computers that run on a perception
  - export ssh_config=subt@azure.perception
  - +extend: robot/perception/transfer/vm-perception
  
  - vm:
      # go to the remote computer, execute the steps
      # bug: make it use env variable
      - +ssh:{ subt:azure-perception:/home/$USER/.ssh/vpn-azure }

      # perception
      - export deploybook_robot=azure.perception
      - +extend: robot/perception/compose/perception
