# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # == build the chonky base ==
  - chonky:
    - cd $SUBT_PATH/$dcompose_relpath
    - thirdparty:
      - cd dockerfiles/thirdparty-software
      - "[ -e aarch64-linux-gnu ] || ./populate_aarch64.sh"
      - "[ -e cuda ] || ./populate_cuda.sh"
    - build_image: # build_image instead of image so regex doesn't do anything stupid
      - docker build -t subt/chonky_l4t -f dockerfiles/perception/services/arm/chonky-base.dockerfile ./dockerfiles
    - clean:
      - cd dockerfiles/thirdparty-software
      - rm -rf aarch64-linux-gnu
      - rm -rf cuda

  # == creating docker images ==
  - image:
    - docker-compose-wrapper $scenario build --force-rm ros-$deploy_system_type-image
    - docker-compose-wrapper $scenario build --force-rm perception-$deploy_system_type-image
    # ignore any error messages (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # == creating docker access containers ==
  - shell:
    - docker-compose-wrapper $scenario -p perception-$deploy_system_type-shell up --force-recreate -d perception-$deploy_system_type-shell

  # == creating docker run containers ==
  - container.run:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-start up --force-recreate -d sim-commander-run
  # any compose command -- user can add '-e arg="launch build-gui"' to specify command
  - container.exec:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-run up --force-recreate -d sim-commander-run-any
