# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - azure:
    # //////////////////////////////////////////////////////////////////////////

      # pull images from the docker registry
      - pull:
        # change the docker context to the ugv azure docker daemon
        - docker context use $DOCKER_CONTEXT
        # pull the docker images from the laptop local registry
        - docker pull $AZURE_REGISTRY/subt-perception-arm:0.1
        # tag the docker images
        - docker tag $AZURE_REGISTRY/subt-perception-arm:0.1 subt/perception-arm:0.1
        # remove the azure docker images
        - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
        # show the docker images
        - docker images
        # change the docker context back to the default docker daemon
        - docker context use default

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////

      # pull images from the docker registry
      - pull:
        # tag the docker images on the basestation registry
        - docker tag subt/perception-arm:0.1 $BASESTATION_REGISTRY/subt-perception-arm:0.1
        # change the docker context to the ugv azure docker daemon
        - docker context use $DOCKER_CONTEXT
        # pull the docker images from the laptop local registry
        - docker pull $BASESTATION_REGISTRY/subt-perception-arm:0.1
        # tag the docker images
        - docker tag $BASESTATION_REGISTRY/subt-perception-arm:0.1 subt/perception-arm:0.1
        # remove the basestation docker images
        - docker rmi $(docker images | grep $BASESTATION_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
        # show the docker images
        - docker images
        # change the docker context back to the default docker daemon
        - docker context use default
        # remove the basestation docker images
        - docker rmi $(docker images | grep $BASESTATION_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
