blacklist: []
build_space: ../../build/ugv/loam/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/ugv/loam
extend_path: /opt/ros/melodic
install: false
install_space: ../../install/ugv/loam/
isolate_install: false
jobs_args: []
log_space: ../../logs/ugv/loam/
make_args: []
source_space: slam
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []