---
# ////////////////////////////////////////////////////////////////////////
# setup localhost
# ////////////////////////////////////////////////////////////////////////
- name: Docker Setup

  # run playbook on the localhost
  hosts: localhost
  connection: local
  become_method: sudo
  become_user: root

  # ////////////////////////////////////////////////////////////////////////
  # setup variables to be shared in tasks
  # ////////////////////////////////////////////////////////////////////////
  vars_files:
    vars/packages.yaml
   
  # ////////////////////////////////////////////////////////////////////////
  # Tasks to execute
  # ////////////////////////////////////////////////////////////////////////
  tasks:
  
  - name: Update get apt packages
    become: true
    apt:
      update_cache: yes

  - name: Install Docker Dependency Packages
    become: true
    apt:
      name: "{{ docker_packages }}"
      state: present
      force_apt_get: yes

  - name: Add official GPG key of Docker
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Save the current Ubuntu release version
    shell: lsb_release -cs
    register: ubuntu_version

  - name: Set right Docker directory
    become: true
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"

  - name: Update apt packages
    become: true
    apt:
      update_cache: yes

  - name: Install Docker
    become: true
    apt:
      name: docker-ce
      state: present
      force_apt_get: yes

  - name: Validate Docker
    become: true
    shell: docker --version
    register: docker_version_out

  - name: Output Validate Docker
    debug:
      msg: "Container Output: {{docker_version_out.stdout}}"

  - name: Test Docker with hello world example
    become: true
    shell: docker run hello-world
    register: hello_world_output

  - name: Show output of hello word example
    debug:
      msg: "Container Output: {{hello_world_output.stdout}}"
