# Install basic dependencies on the remote VM
- include: tasks/robothost.yaml

# TODO: setup azure vpn keys?

# Install docker & docker-tools on the remote VM
- include: tasks/docker.yaml
- include: tasks/docker-tools.yaml

# TODO: add variable to enable/disable
# Install nvidia docker only on gpu hosts
- include: tasks/docker-nvidia.yaml

# Install teamviewer and GNOME desktop on the remote VM
- include: tasks/teamviewer.yaml

# Install azure tools
- include: tasks/azure.yaml

# install ros on VM localhost
- include: tasks/ros.yaml

# TODO: verify all tools have been installed
