
# Install basic dependencies on the remote VM
- include: tasks/robothost.yaml

# Install docker & docker-tools on the remote VM
- include: tasks/docker.yaml
- include: tasks/docker-tools.yaml

# Install nvidia docker only on gpu hosts
- include: tasks/docker-nvidia.yaml

# Install teamviewer and GNOME desktop on the remote VM
- include: tasks/gnome.yaml
- include: tasks/teamviewer.yaml

# Clones the deploy repo on the remote VM (can take 30 minutes)
# You do not need to clone the repo on the remote VM manually, this command will do that for you.
- include: tasks/git-config.yaml
- include: tasks/git-clone.yaml
