---
  # ////////////////////////////////////////////////////////////////////////
  # setup localhost
  # ////////////////////////////////////////////////////////////////////////
  - name: Localhost Setup
    
    # setup variables to be shared in tasks
    vars_files:
      vars/packages.yaml
  
    # setup hosts to run commands as
    hosts:
      - localhost
      - basestation
      - ugv
      - uav
    become_method: sudo
    become_user: root
    
    # ////////////////////////////////////////////////////////////////////////
    # Tasks to execute
    # ////////////////////////////////////////////////////////////////////////
    tasks:
      
      # ////////////////////////////////////////////////////////////////////////
      # Install Base Packages
      # ////////////////////////////////////////////////////////////////////////
      - name: Update get apt packages
        become: true
        apt:
          force: yes          # force yes
          force_apt_get: yes
          install_recommends: yes
          update_cache: yes   # force apt-get update

      - name: Install Ubuntu Prerequisite Packages
        become: true
        apt:
          name: "{{ prereq_packages }}"
          state: present
          force: yes          # force yes
          force_apt_get: yes
          install_recommends: yes
          update_cache: yes   # force apt-get update
      
      - name: Install Python Prerequisite Packages
        pip:
          name: "{{ pip_packages }}"
          extra_args: --user

      # ////////////////////////////////////////////////////////////////////////
      # Install Remote Desktop
      # ////////////////////////////////////////////////////////////////////////
      
      - name: Install RDP Prerequisite Packages
        become: true
        ignore_errors: yes
        apt:
          name: "{{ rdp_packages }}"
          state: present
          force: yes  # force yes
          force_apt_get: yes
          install_recommends: yes
          update_cache: yes   # force apt-get update
      
      - name: Enable service xrdp
        become: true
        systemd:
          name: xrdp
          state: started  # make sure service is running
          enabled: yes    # start service on boot
          masked: no
      
      - name: Add session to xsession
        shell: echo xfce4-session >~/.xsession

      - name: Restart service xrdp
        become: true
        systemd:
          name: xrdp
          state: restarted  # make sure service is running
          enabled: yes    # start service on boot
          masked: no
