blacklist: []
build_space: ../../build/basestation/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/basestation/
extend_path: /home/developer/deploy_ws/devel/basestation/common
install: false
install_space: ../../install/basestation/
isolate_install: false
jobs_args: []
log_space: ../../logs/basestation/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
