# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - perception:
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/perception
      - rm -rf ~/deploy_ws/build/perception
      - rm -rf ~/deploy_ws/install/perception
      - rm -rf ~/deploy_ws/logs/perception

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set perception-x86
        - catkin config
        - catkin build --force-cmake

      - perception:
        - deps:
          # build perception deps
          - cd ~/deploy_ws/src/perception/deps/catkin
          - rm -f .catkin_tools/profiles/profiles.yaml
          - catkin profile list
          -  catkin profile set perception-x86
          - catkin config
          - catkin build --force-cmake
        - objdet:
          # build objdet
          - cd ~/deploy_ws/src/perception/
          - rm -f .catkin_tools/profiles/profiles.yaml
          - catkin profile list
          -  catkin profile set perception-x86
          - catkin config
          - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set perception-x86
        - catkin config
        - catkin build --force-cmake