# //////////////////////////////////////////////////////////////////////////////
- local:
  # //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/local/.local.env

  # ////////////////////////////////////////////////////////////////////////////
  - ugv:
  # ////////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - ugv1:
    # ////////////////////////////////////////////////////////////////////////////
      # source the computer-level scenario file

      - export filename=systems/local/ugv1
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - registry:
        - +extend: systems/local/ugv/vm/registry
      - compose:
        - core:
          - +extend: systems/local/ugv/vm/compose
      - catkin:
        - core:
          - +docker:ugv1-sim-shell
          - +extend: systems/local/ugv/vm/catkin.core

    # ////////////////////////////////////////////////////////////////////////////
    - ugv2:
    # ////////////////////////////////////////////////////////////////////////////
      # source the computer-level scenario file

      - export filename=systems/local/ugv2
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - registry:
        - +extend: systems/local/ugv/vm/registry
      - compose:
        - +extend: systems/local/ugv/vm/compose
      - catkin:
        - +docker:ugv2-sim-shell
        - +extend: systems/local/ugv/vm/catkin.core

    # ////////////////////////////////////////////////////////////////////////////
    - ugv3:
    # ////////////////////////////////////////////////////////////////////////////
      # source the computer-level scenario file

      - export filename=systems/local/ugv3
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - registry:
        - +extend: systems/local/ugv/vm/registry
      - compose:
        - +extend: systems/local/ugv/vm/compose
      - catkin:
        - +docker:ugv3-sim-shell
        - +extend: systems/local/ugv/vm/catkin.core
