- pwd

# //////////////////////////////////////////////////////////////////////////////
# subt_ws is in 'jenkins' home directory
- 'export SUBT_SRC=$PWD/../'
- 'export SUBT_WS=$PWD/../../'
# darpa_ws is in 'jenkins' home directory
- 'export DARPA_WS=/home/jenkins/darpa_ws/'
- 'export DARPA_SRC=$DARPA_WS/src'

# //////////////////////////////////////////////////////////////////////////////
### build the dapra subt repo -- so that airlab_subt builds against the most updated version of darpa_subt
- darpa:
  - 'echo "darpa dir: " && pwd'  
  - source:
    # clone sources
    - cd ~
    - mkdir -p darpa_ws/src
    - cd darpa_ws/
    - wget https://s3.amazonaws.com/osrf-distributions/subt_robot_examples/releases/subt_robot_examples_latest.tgz
    - tar xvf subt_robot_examples_latest.tgz
    - cd src
    # download the cmu 'subt_robots'
    - git clone git@bitbucket.org:cmusubt/subt_robots.git
    # download darpa 'subt'
    - hg clone https://bitbucket.org/osrf/subt
    - cd subt
    # checkout specific commit that builds with 'catkin build'
    - hg update b7c3a0e6072b
    
  - build:
    # build sources
    - cd $DARPA_WS
    - catkin init
    - catkin config --extend /opt/ros/melodic/
    - catkin config --install
    - catkin config -a --cmake-args -DCMAKE_BUILD_TYPE=Release
    - catkin build --no-status

# //////////////////////////////////////////////////////////////////////////////
### build the airlab subt repo
- subt:
  - 'echo "subt dir: " && pwd'  
  - source:
    # clone source
    - cd ..
    - ln -s planning_workspace/rosinstall/integration_tests.rosinstall .rosinstall
    - wstool update
  - build:
    # build sources
    - cd $SUBT_WS
    - catkin init
    - catkin config --extend $DARPA_WS/install/
    - catkin config -a --cmake-args -DCMAKE_BUILD_TYPE=Release
    - catkin build --no-status

