# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # push images to the local docker registry
  - push:
    # tag the docker images
    - docker tag subt/ugv:ros $AZURE_REGISTRY/subt-ugv-ros
    - docker tag subt/ugv:ppc $AZURE_REGISTRY/subt-ugv-ppc
    - docker tag subt/ugv:nuc $AZURE_REGISTRY/subt-ugv-nuc
    # push the docker images to the local registry
    - docker push $AZURE_REGISTRY/subt-ugv-ros
    - docker push $AZURE_REGISTRY/subt-ugv-ppc
    - docker push $AZURE_REGISTRY/subt-ugv-nuc

  # pull images from the docker registry
  - pull:
    # pull the docker images from the laptop local registry
    - docker pull $AZURE_REGISTRY/subt-ugv-ros
    - docker pull $AZURE_REGISTRY/subt-ugv-ppc
    - docker pull $AZURE_REGISTRY/subt-ugv-nuc
    # tag the docker images
    - docker tag $AZURE_REGISTRY/subt-ugv-ros subt/ugv:ros
    - docker tag $AZURE_REGISTRY/subt-ugv-ppc subt/ugv:ppc
    - docker tag $AZURE_REGISTRY/subt-ugv-nuc subt/ugv:nuc