# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # push images to the local docker registry
    - push:
      # change the docker context to the ugv azure docker daemon
      - docker context use $DOCKER_CONTEXT
      # tag the docker images
      - docker tag subt/ugv:ros $AZURE_REGISTRY/subt-ugv-ros
      - docker tag subt/ugv:ppc $AZURE_REGISTRY/subt-ugv-ppc
      - docker tag subt/ugv:nuc $AZURE_REGISTRY/subt-ugv-nuc
      # push the docker images to the local registry
      - docker push $AZURE_REGISTRY/subt-ugv-ros
      - docker push $AZURE_REGISTRY/subt-ugv-ppc
      - docker push $AZURE_REGISTRY/subt-ugv-nuc
      # remove the docker images from the local registry
      - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
      # change the docker context back to the default docker daemon
      - docker context use default

    # pull images from the docker registry
    - pull:
      # change the docker context to the ugv azure docker daemon
      - docker context use $DOCKER_CONTEXT
      # pull the docker images from the laptop local registry
      - docker pull $AZURE_REGISTRY/subt-ugv-ros
      - docker pull $AZURE_REGISTRY/subt-ugv-ppc
      - docker pull $AZURE_REGISTRY/subt-ugv-nuc
      # tag the docker images
      - docker tag $AZURE_REGISTRY/subt-ugv-ros subt/ugv:ros
      - docker tag $AZURE_REGISTRY/subt-ugv-ppc subt/ugv:ppc
      - docker tag $AZURE_REGISTRY/subt-ugv-nuc subt/ugv:nuc
      # remove the docker images from the local registry
      - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
      # show the docker images
      - docker images
      # change the docker context back to the default docker daemon
      - docker context use default
