# //////////////////////////////////////////////////////////////////////////
# transfer to remote host
# TODO: cleanup
# //////////////////////////////////////////////////////////////////////////
- transfer:
  # connections
  - 'export user=kat'
  - 'export host=azure-vm-example'
  
  # rsync options
  - 'export copy_opts="-avzh --delete --exclude=src/perception/object_detection/inference/data/models/" '

  # paths
  - 'export LOCAL_DEPLOY_PATH=//home/katarina/airlab/infrastructure/deploy-restructure/deploy-new/src'
  - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/'
  
  - export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH $user@$host:$REMOTE_DEPLOY_PATH "
  
  - to:
    # create the remote directory
    - ssh $user@$host -i ~/.ssh/azure/vm-keys/example_id_rsa "mkdir -p $REMOTE_DEPLOY_PATH"
    
    # copy command
    - 'export copy_cmd=$copy_to'

  # evaluate copy
  - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
  - eval $copy_cmd

# //////////////////////////////////////////////////////////////////////////
# local system interface to deployer commander run commands
# //////////////////////////////////////////////////////////////////////////
- host:
  - container-run-any:
    - +extend: azure/basestation/run/basestation

# //////////////////////////////////////////////////////////////////////////
# docker container interface to deployer commander run commands
# //////////////////////////////////////////////////////////////////////////
- docker:
  # TODO: scenario file
  - +ssh:{ kat:azure-vm-example:/home/$USER/.ssh/azure/vm-keys/example_id_rsa }

  # add '--force-rm '
  - image:
    - docker-compose-wrapper $scenario build ros-image
    - docker-compose-wrapper $scenario build gui-image
    # any compose command -- user can add '-e arg="launch build-gui"' to specify command
  - container:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-start up --force-recreate -d gui-commander-run
  - container-run-any:
    - docker-compose-wrapper $scenario -p ${deploybook_run}-run up --force-recreate -d gui-commander-run-any
  - shell:
    - docker-compose-wrapper $scenario up --force-recreate -d ros-shell
    - docker-compose-wrapper $scenario up --force-recreate -d gui-shell

