# //////////////////////////////////////////////////////////////////////////////
- local:
# //////////////////////////////////////////////////////////////////////////////

  - +extend: common/git
  - test:
    - +docker:perception-gpu-shell
    - echo hi
    - env
