# //////////////////////////////////////////////////////////////////////////////
- robots:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/robot/.robot.env

  # ////////////////////////////////////////////////////////////////////////////
  - basestation:
  # ////////////////////////////////////////////////////////////////////////////
    - +extend: systems/robot/basestation/localhost/registry

  # ////////////////////////////////////////////////////////////////////////////
  - basestation.cpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/robot/basestation-cpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - +extend: systems/robot/basestation/localhost/compose
    - catkin:
      - +docker:basestation-cpu-shell
      - +extend: systems/robot/basestation/localhost/catkin

  # ////////////////////////////////////////////////////////////////////////////
  - basestation.gpu:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/robot/basestation-gpu
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - +extend: systems/robot/basestation/localhost/compose
    - catkin:
      - +docker:basestation-gpu-shell
      - +extend: systems/robot/basestation/localhost/catkin