# //////////////////////////////////////////////////////////////////////////////
- robots:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/robot/.robot.env

  # ////////////////////////////////////////////////////////////////////////////
  - basestation:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/robot/basestation
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - +extend: systems/robot/basestation/localhost/compose
    - catkin:
      - +docker:basestation-shell
      - +extend: systems/robot/basestation/localhost/catkin
