# //////////////////////////////////////////////////////////////////////////////
- robots:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/robots/.robots.env

  # ////////////////////////////////////////////////////////////////////////////
  - basestation:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/robots/basestation
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    # extend
    - +extend: systems/azure/ugv/vm/compose
