# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - nuc.planning:
  # ////////////////////////////////////////////////////////////////////////////
    - +docker:nuc-shell
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/ugv/nuc
      - rm -rf ~/deploy_ws/build/ugv/nuc
      - rm -rf ~/deploy_ws/install/ugv/nuc
      - rm -rf ~/deploy_ws/logs/ugv/nuc

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-nuc
        - catkin config
        - catkin build --force-cmake

      - ugv:
        - cd ~/deploy_ws/src/ugv
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-nuc
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-nuc
        - catkin config
        - catkin build --force-cmake

  # ////////////////////////////////////////////////////////////////////////////
  - nuc.slam:
  # ////////////////////////////////////////////////////////////////////////////
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/ugv/slam
      - rm -rf ~/deploy_ws/build/ugv/slam
      - rm -rf ~/deploy_ws/install/ugv/slam
      - rm -rf ~/deploy_ws/logs/ugv/slam

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - slam:
        - cd ~/deploy_ws/src/ugv
        - rm -f .catkin_tools/profiles/profiles.yaml
        # ignore slam/devel repos
        - touch slam/devel/loam_velodyne_16/CATKIN_IGNORE
        - touch slam/devel/velodyne_driver_16_32/CATKIN_IGNORE
        - catkin profile list
        - catkin profile set ugv-slam
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-slam
        - catkin config
        - catkin build --force-cmake

  # ////////////////////////////////////////////////////////////////////////////
  - nuc.perception:
  # ////////////////////////////////////////////////////////////////////////////
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/ugv/perception
      - rm -rf ~/deploy_ws/build/ugv/perception
      - rm -rf ~/deploy_ws/install/ugv/perception
      - rm -rf ~/deploy_ws/logs/ugv/perception

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-nuc-perception
        - catkin config
        - catkin build --force-cmake

      - perception:
        - cd ~/deploy_ws/src/perception
        - rm -f .catkin_tools/profiles/profiles.yaml
        # ignore slam/devel repos
        - catkin profile list
        - catkin profile set nuc
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-nuc-perception
        - catkin config
        - catkin build --force-cmake
