# ////////////////////////////////////////////////////////////////////////////
- robot.nuc.catkin:
# ////////////////////////////////////////////////////////////////////////////
  - cd $SUBT_PATH/
  - pwd

  # ////////////////////////////////////////////////////////////////////////////
  # perform all tasks that involve 'building'
  - build:
  # ////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - start:
    # //////////////////////////////////////////////////////////////////////////
      - common:
        - cd common/
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile set ${deploybook_catkin_profile}
        - catkin build --force-cmake
      - nuc:
        - cd ugv/nuc/
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile set ${deploybook_catkin_profile}
        - catkin build --force-cmake
      # TODO:
      # - launch:
      #   - cd $DEPLOY_SRC/operations/launch/
      #   - rm -f .catkin_tools/profiles/profiles.yaml
      #   - catkin profile set ${computer_type_t}-basestation
      #   - catkin build --force-cmake
      #   - catkin clean -b --yes

    # //////////////////////////////////////////////////////////////////////////
    - stop:
    # //////////////////////////////////////////////////////////////////////////
      - echo "Nothing to stop, everything is done."
