# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - docker-compose-wrapper $scenario build ros-image
    - docker-compose-wrapper $scenario build nuc-image

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    - shell:
      # - docker-compose-wrapper $scenario -p ros-shell up --force-recreate -d ros-shell
      - docker-compose-wrapper $scenario -p nuc-shell up --force-recreate -d nuc-shell
    # stopping containers
    - stop:
      - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - docker rm -f $(docker ps -a -q)
