# //////////////////////////////////////////////////////////////////////////
# docker container interface to deployer commander run commands
# //////////////////////////////////////////////////////////////////////////
- docker:
  # add '--force-rm '
  - image:
    - docker-compose-wrapper $scenario build ros-image
    - docker-compose-wrapper $scenario build nuc-image
  - shell:
    # - docker-compose-wrapper $scenario -p ros-shell up --force-recreate -d ros-shell
    - docker-compose-wrapper $scenario -p nuc-shell up --force-recreate -d nuc-shell

  # == docker registry ==

  # pull images from the docker registry
  - pull:
    # pull the docker images from the laptop local registry
    - docker pull $BASESTATION_REGISTRY/subt-ugv-ros
    - docker pull $BASESTATION_REGISTRY/subt-ugv-nuc
    # tag the docker images
    - docker tag $BASESTATION_REGISTRY/subt-ugv-ros subt/ugv:ros
    - docker tag $BASESTATION_REGISTRY/subt-ugv-nuc subt/ugv:nuc