blacklist:
- xsens_cpp_driver
- xsense_driver
- receive_xsens
build_space: ../../build/ugv/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/ugv/
extend_path: ../../devel/ugv/common
install: false
install_space: ../../install/ugv/
isolate_install: false
jobs_args: []
log_space: ../../logs/ugv/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
