####################################################################################################
# robot 1 configuration file
- r1:
####################################################################################################

  ##################################################################################################
  - basestation:
  ##################################################################################################
    - 'export YELLOW="\033[1;33m"'
    - 'export BLUE="\033[1;36m"'

    ################################################################################################
    - docker:
    ################################################################################################

      ####################################################
      # setup
      ####################################################
      - hostname
      - whoami
      - pwd
      
      ####################################################
      # path setup
      - 'export DEPLOY_WS=/home/katarina/airlab/subt/deploy_ws/'
      - 'export DEPLOY_SRC=/home/katarina/airlab/subt/deploy_ws/src/'
      - 'export DOCKER_CONFIG=field/basestation'
      - 'export DOCKER_CONFIG_PATH=docker/env'
      
      ####################################################
      # print docker configuration information
      ####################################################
      - print.build:
        - echo -e "\n${BLUE} == Docker images to create == \n" ;
        - echo -e "\n${YELLOW}\t** nested docker env configs used ** \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/osrf.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/field/basestation.config \n" ;
        - echo -e "\n${YELLOW}\t** subt docker env ** \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DEPLOY_SRC$DOCKER_CONFIG_PATH/field/basestation.config \n" ;
        - echo -e "\n${YELLOW} ** Remember to always transfer any changed configuration files! ** \n";
      - print.run:
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG \n" ;
        - echo -e "\n${YELLOW}\t local env path -> \t $DEPLOY_SRC$DOCKER_CONFIG_PATH/field/basestation.config \n" ;
        - echo -e "\n${YELLOW}\t remote env filepath -> \t $DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config \n"
        - while IFS= read line;
          do 
            echo -e ${BLUE} "\t$line";
          done < "$DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config"

      ####################################################
      # build docker images
      ####################################################
      - cd $DEPLOY_SRC/docker/scripts
      - image:
        - 'export BUILD_ARGS="--force" '
        - subt:
          - ./build.bash --env field/basestation.ros $BUILD_ARGS
          - ./build.bash --env field/basestation.planning $BUILD_ARGS

      ####################################################
      # start docker images
      ####################################################
      - start:
        - 'export START_ARGS=" " '
        - ./run.bash --env field/basestation.planning $START_ARGS

      ####################################################
      # stop docker images
      ####################################################
      - stop:
        - 'export STOP_ARGS="--stop --containers " '
        - ./clean.bash --env field/basestation.planning $STOP_ARGS
      
      - remove:
        - 'export STOP_ARGS="--remove --containers " '
        - ./clean.bash --env field/basestation.planning $STOP_ARGS
      
      ####################################################
      # delete docker images & corresponding containers
      ####################################################
      - delete:
        - 'export DELETE_ARGS="--containers" '
        - ./clean.bash --env field/basestation.ros $DELETE_ARGS
        - ./clean.bash --env field/basestation.planning $DELETE_ARGS
      
      ####################################################
      # misc.
      ####################################################
      - dangling:
        - docker rmi -f $(docker images -f "dangling=true" -q)
      
    ################################################################################################
    - deploy:
    ################################################################################################
      # only docker container on basestation, no ssh
      - +docker:subt-deploy
      
      - hostname
      - whoami
      - pwd
      - 'export DEPLOY_SRC=/home/developer/deploy_ws/src'
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - cd $DEPLOY_SRC
  
      ####################################################
      # clone workspaces
      ####################################################
      - clone:

        # update the git submodule
        - submodule:
          - git submodule init planning/planning_workspace/
          - git submodule update planning/planning_workspace/
        
        # clone & update the planning workspace
        - cd planning/
        
        # apt install any thirdparty deps
        - install_deps:
          - ./planning_workspace/install_dependencies.sh

        # setup the rosinstalls
        - rosinstall:
          - if [ -f .rosinstall ]; then
              rm .rosinstall;
            fi
          - ln -s planning_workspace/rosinstall/deploy/deploy.rosinstall .rosinstall
          - cd deps/catkin
          - if [ -f .rosinstall ]; then
              rm .rosinstall;
            fi
          - ln -s ../../planning_workspace/rosinstall/deploy/deploy-deps.rosinstall .rosinstall
        
        # wstool update the workspaces
        - wstool:
          - planning:
            - wstool info
            - wstool update
          - deps:
            - cd deps/catkin
            - wstool info
            - wstool update

      ####################################################
      # build workspaces
      ####################################################
      - build:
        - cd planning/
        
        # build the deps workspaces
        - deps:
          - cd deps/catkin
          - catkin build
        
        # install the robot_examples
        - robot_examples:
          - cd $DEPLOY_SRC/../install/planning
          - wget https://s3.amazonaws.com/osrf-distributions/subt_robot_examples/releases/subt_robot_examples_latest.tgz
          - tar xf subt_robot_examples_latest.tgz -C deps --strip-components 1
        
        # build planning workspace
        - planning:
          - catkin build

        # build the launch workspace
        - launch:
          - cd $DEPLOY_SRC/launch
          - catkin build

      ####################################################
      # clean workspaces
      ####################################################
      - clean:
        - launch:
          - cd launch
          - catkin clean
        - cd planning/
        - planning:
          - catkin clean -y
        - deps:
          - cd deps/catkin
          - catkin clean -y

      ####################################################
      # remove workspaces
      ####################################################
      - remove:
        - cd planning/
        - if [ -f .rosinstall ]; then
            rm .rosinstall;
          fi
        - if [ -f deps/catkin/.rosinstall ]; then
            rm deps/catkin/.rosinstall
          fi
        - git:
          - git submodule deinit planning/planning_workspace/

      ####################################################
      # launch workspaces
      ####################################################
      - launch:
        ### == user can modify ==
        
        # launch configuration variables
        - 'export host=basestation'
        - 'export config=ugv1'
        
        ### == user can modify done. ==

        # read the launch configuration params
        - export config_data=""
        - export CONFIG_FILE="$DEPLOY_SRC/launch/robot_launch_scripting/config/$config.config"
        - while IFS='' read -r line || [[ -n "$line" ]]; do
            if [ ! "${line:0:1}" == "#" ]; then
              config_data="$config_data $line";
            fi
          done < "$CONFIG_FILE";
        - echo $config_data
        
        - start:
          # start the tmux sessions
          - tmux new  -s ${host}_launch_${config} -d
          - tmux new -s ${host}_check_roscore -d

          # source the planning ws
          - tmux send -t ${host}_launch_${config} 'source $DEPLOY_WS/devel/planning/launch/setup.bash' ENTER
          - tmux send -t ${host}_check_roscore 'source $DEPLOY_WS/devel/planning/launch/setup.bash' ENTER

          # launch commands to run planning ws
          - tmux send -t ${host}_launch_${config} 'roslaunch basestation_gui_python gui.launch ' ENTER
          - echo "Launch deployed in tmux session ${host}_launch_${config}"
          
        - stop:
          # remove all the tmux sessions
          - tmux kill-session -t ${host}_launch_${config}
          - tmux kill-session -t ${host}_check_roscore
          - tmux send -t ${host}_launch_${config} 'rosnode kill -a' ENTER
          - tmux send -t ${host}_launch_${config} 'pkill -f ros' ENTER
          - tmux send -t ${host}_launch_${config} 'rosnode list' ENTER

        - rosclean:
          - source $DEPLOY_WS/devel/planning/repo/setup.bash
          - ps aux | grep ros
          - rosnode kill
          - pkill -f ros
          - rosnode list
          
          