####################################################################################################
# robot 1 configuration file
- r1:
####################################################################################################

  ##################################################################################################
  - xavier:
  ##################################################################################################
    - 'export YELLOW="\033[1;33m"'
    - 'export BLUE="\033[1;36m"'

    ################################################################################################
    # copy deploy repo from basestation to r1.nuc
    - transfer:
    ################################################################################################
      
      ### == user can modify ==
      
      # connections
      - 'export user=nvidia'
      - 'export host=xavier'
      - 'export HOP_HOST=robot@planning-pc'
      
      # paths
      - 'export LOCAL_DEPLOY_PATH=/home/$USER/subt/deploy_ws/src'
      - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/'
      
      # rsync options
      - 'export copy_opts="-avzh --exclude=src/planning" '
      - export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH -e 'ssh $HOP_HOST ssh ' $user@$host:$REMOTE_DEPLOY_PATH "
      - export copy_from="rsync $copy_opts --exclude 'src/planning' $user@$host:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH "

      ### == user can modify done. ==

      ####################################################
      # perform actual transfer. do not change.
      ####################################################
      - print:
        # print
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
        - echo -e "\n${YELLOW}\t transfer to -> \t $copy_to \n" ;

      - transfer:
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;

        # transfer TO remote host
        - to:
          # create the remote directory
          - ssh $HOP_HOST ssh $user@$host "mkdir -p $REMOTE_DEPLOY_PATH"
          
          # copy command
          - 'export copy_cmd=$copy_to'

        # transfer FROM remote host
        - from:
          - 'export copy_cmd=$copy_from'

        # evaluate copy
        - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
        - eval $copy_cmd
      
      # delete remote deploy workspace
      - delete:
        - ssh $user@$host "rm -rf $REMOTE_DEPLOY_PATH"

    ################################################################################################
    - docker:
    ################################################################################################
      ####################################################
      # ssh into the remote robot
      ####################################################
      - +ssh:{robot:planning-pc:/home/mtatum/.ssh/planning_pc }
      - +ssh:{nvidia:xavier:/home/nvidia/.ssh/nuc }
      
      ####################################################
      # setup
      ####################################################
      - hostname
      - whoami
      - pwd
      
      ####################################################
      # path setup
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src/'

      - 'export DOCKER_CONFIG=subt/subt'
      - 'export DOCKER_CONFIG_PATH=docker/env'
      
      ####################################################
      # print docker configuration information
      ####################################################
      - print.build:
        - echo -e "\n${BLUE} == Docker images to create == \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/osrf.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/subt.config \n" ;
        - echo -e "\n${YELLOW} ** Remember to always transfer any changed configuration files! ** \n";
      - print.run:
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG \n" ;
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG_PATH/subt/subt.config \n" ;
        - echo -e "\n${YELLOW}\t subt remote env filepath -> \t $DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config \n"
        - while IFS= read line;
          do 
            echo -e ${BLUE} "\t$line";
          done < "$DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config"

      ####################################################
      # build docker images
      ####################################################
      - cd $DEPLOY_SRC/docker/scripts
      - build:
        - 'export BUILD_ARGS="--force" '
        - osrf:
          - echo $LANG
          - ./build.bash --env osrf/ros $BUILD_ARGS
          - ./build.bash --env osrf/osrf $BUILD_ARGS
        - subt:
          - ./build.bash --env subt/ros $BUILD_ARGS
          - ./build.bash --env subt/subt $BUILD_ARGS

      ####################################################
      # start docker images
      ####################################################
      - start:
        - 'export START_ARGS=" --no-nvidia " '
        - ./run.bash --env subt/subt $START_ARGS

      ####################################################
      # stop docker images
      ####################################################
      - stop:
        - 'export STOP_ARGS="--stop --containers " '
        - ./clean.bash --env subt/subt $STOP_ARGS
      
      - remove:
        - 'export STOP_ARGS="--remove --containers " '
        - ./clean.bash --env subt/subt $STOP_ARGS
      
      ####################################################
      # delete docker images & corresponding containers
      ####################################################
      - clean:
        - 'export DELETE_ARGS="--containers" '
        - ./clean.bash --env subt/subt $DELETE_ARGS
        - ./clean.bash --env subt/ros $DELETE_ARGS
        - ./clean.bash --env osrf/osrf $DELETE_ARGS
        - ./clean.bash --env osrf/ros $DELETE_ARGS
      
      ####################################################
      # misc.
      ####################################################
      - dangling:
        - docker rmi -f $(docker images -f "dangling=true" -q)
      
    ################################################################################################
    - deploy:
    ################################################################################################
      - +ssh:{robot:planning-pc:/home/mtatum/.ssh/planning_pc }
      - +ssh:{nvidia:xavier:/home/nvidia/.ssh/nuc }
      # - +docker:subt  # no docker in xavier
      
      - hostname
      - whoami
      - pwd
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src'
      - cd $DEPLOY_SRC

      ####################################################
      # clone workspaces
      ####################################################
      - clone:

        # update the git submodule
        - submodule:
          - git submodule update perception/object_detection
          - git submodule update perception/object_detection/base_main_class
          - git submodule update perception/object_detection/basestation_gui_python
          - git submodule update perception/deps/catkin/basestation_gui_python
          - git submodule update perception/deps/catkin/darpa_command_post

        # clone & update the planning workspace
        - cd perception/
        
        - rosdep:
          - deps:
            - source /opt/ros/melodic/setup.bash
            - cd deps/catkin
            - rosdep install --from-paths . --ignore-src --rosdistro melodic -y
          - ws:
            - source ../../devel/perception/deps/setup.bash
            - rosdep install --from-paths . --ignore-src --rosdistro melodic -y

      ####################################################
      # build workspaces
      ####################################################
      - build:
        - cd perception/
        
        # build the deps workspaces
        - deps:
          - cd deps/catkin
          - catkin build
        
        # build planning workspace
        - ws:
          - catkin build

      ####################################################
      # clean workspaces
      ####################################################
      - clean:
        - cd perception/
        - repo:
          - catkin clean -y
        - deps:
          - cd deps/catkin
          - catkin clean -y

      ####################################################
      # remove workspaces
      ####################################################
      - remove:
        - cd perception/
        - git:
          - git submodule deinit perception/

      ####################################################
      # stop all launches
      ####################################################
      - stop:
        - rosnode kill -a
        - pkill -f ros
        - rosnode list

      