# email configuration
emails: [kcujic@andrew.cmu.edu]
# ignore sending to anyone: 'email: false'
email: true

# slack notifications
slack:
  started: true
  success: true
  failure: true
  # available: theairlab, minerobots
  subdomain: "minerobots"

# slurm node to use on every slurm call
slurm:
  node: "roberto"

# docker configuration
docker:
  # docker image to use
  image: "subt/base:latest"

  # slurm options
  slurm:
    - "-t 0-01:00"

  # days to wait until to destroy the container
  destroy: 2

  # enabling docker gpu access
  # true/false forces using 'nvidia-docker'/'docker'
  gpu: true

  # volumes to mount on the container
  volumes:
    # - "/home/$USER:/home/$USER"
    
  # docker create options
  options:
    # - "--cpuset-cpus=\"0-36\""
    # - "--privileged"
    # - "--gateway 203.0.113.254"
    # - "--net iptastic"
    # - "--ip 203.0.113.2"
    # - "-p 127.0.0.1:8001:8001"
    # - "--device /dev/nvidia-uvm:/dev/nvidia-uvm"
    - "--net=host"
    - "-e DISPLAY"
    - "--ulimit nofile=1048576:1048576" 

# phase file for build to run
phase: ci/phase/default.yaml

# jenkins stages configuration
stages: [source, build]

# source stage
source:
  timeout: 100000
  messages: "clone the darpa, subt ws and their dependencies"
  sections: [darpa.source, subt.source]
  slurm:
    - "-t 0-01:00"
    - "-c 4"

# build stage
build:
  timeout: 100000
  messages: "build the darpa, subt ws"
  sections: [darpa.build, subt.build]
  slurm:
    - "-t 0-02:00"
    - "-c 4"

# build stage
# test:
#   timeout: 100000
#   messages: "integration tests"
#   sections: [test.integration]
#   slurm:
#     - "-t 0-02:00"
#     - "-c 8"
#     # - "-p gpu --gres=gpu:1"
