- ugv:
  - cd ugv
  - ppc:
    # remove
    - git submodule deinit -f planning-pc
    # re-clone
    - cd planning-pc/
    - git submodule update --init --recursive .
    - git clean -d -f -f
  - nuc:
    # remove
    - git submodule deinit -f nuc
    # re-clone
    - cd nuc
    - git submodule update --init --recursive .
    - git clean -d -f -f

  # reset the simulation repo.
  - cd $SUBT_PATH/ugv/
  - git submodule deinit -f simulation
  - cd simulation
  - git submodule update --init --recursive .
  - git clean -d -f -f
