- basestation:
  # remove
  - git submodule deinit -f basestation
  # re-clone
  - cd basestation
  - git submodule update --recursive --init .
  - git clean -d -f -f

- common:
  # remove
  - git submodule deinit -f common
  # re-clone
  - cd common
  - git submodule update --recursive --init .
  - git clean -d -f -f
  # git lfs steps
  - cd communication_manager
  - git lfs fetch
  - git lfs pull
  - git lfs install

- operations:
  - docker:
    # remove
    - git submodule deinit -f operations/deploy/docker
    # re-clone
    - git submodule update --recursive --init operations/deploy/docker
    - cd operations/deploy/docker
    - git clean -d -f -f

- perception:
  # remove
  - git submodule deinit -f perception
  # re-clone
  - cd perception
  - git submodule update --recursive --init .
  - git clean -d -f -f
  - cd object_detection
  - git submodule update --recursive --init .
  - git clean -d -f -f

- subt_launch:
  # remove
  - git submodule deinit -f subt_launch
  # re-clone
  - cd subt_launch
  - git submodule update --recursive --init .
  - git clean -d -f -f
