# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - ros:
      - docker-compose-wrapper $scenario build --force-rm ros-image
    - ppc:
      - docker-compose-wrapper $scenario build --force-rm ppc-image
    - nuc:
      - docker-compose-wrapper $scenario build --force-rm nuc-image
    - sim:
      - docker-compose-wrapper $scenario build --force-rm ugv-sim-image
    # ignore any build errors (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    - shell:
      # always create the default network if does not exist
      - echo "Docker network subnet is $LOCAL_NETWORK_SUBNET"
      - echo "Docker network ip range is $LOCAL_NETWORK_IP_RANGE"
      - docker network create -d bridge robots --subnet=$LOCAL_NETWORK_SUBNET --ip-range=$LOCAL_NETWORK_IP_RANGE || true
      - ppc:
        - docker-compose-wrapper $scenario -p ppc-shell up --force-recreate -d ppc-shell
      - nuc:
        - docker-compose-wrapper $scenario -p nuc-shell up --force-recreate -d nuc-shell
      - sim:
        - docker-compose-wrapper $scenario -p ugv-sim-shell up --force-recreate -d ${COMPUTER}-sim-shell

    # stopping containers
    - stop:
      - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - docker rm -f $(docker ps -a -q)