# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # == creating docker images ==
  - image:
    - ros:
      - docker-compose-wrapper $scenario build --force-rm ros-image
    - ppc:
      - docker-compose-wrapper $scenario build --force-rm ppc-image
    - nuc:
      - docker-compose-wrapper $scenario build --force-rm nuc-image
    - sim:
      - docker-compose-wrapper $scenario build --force-rm ugv-sim-image
    # ignore any build errors (in case there are no dangling images)
    - docker rmi -f $(docker images -f "dangling=true" -q) 2&1> /dev/null

  # == creating docker access containers ==
  - container:
    - shell:
      - ppc:
        - docker-compose-wrapper $scenario -p ppc-shell up --force-recreate -d ppc-shell
      - nuc:
        - docker-compose-wrapper $scenario -p nuc-shell up --force-recreate -d nuc-shell
      - sim:
        - docker-compose-wrapper $scenario -p ugv-sim-shell up --force-recreate -d ugv-sim-shell
    # == creating docker access containers ==
    # stopping containers
    - stop:
      - all:
        - docker stop $(docker ps -a -q)
      - ppc:
        - docker stop ppc-shell
      - nuc:
        - docker stop nuc-shell
      - sim:
        - docker stop sim-shell
    # removing containers
    - rm:
      - all:
        - docker rm $(docker ps -a -q)
      - ppc:
        - docker rm ppc-shell
      - nuc:
        - docker rm nuc-shell
      - sim:
        - docker rm sim-shell

  # == docker registry ==

  # push images to the local docker registry
  - push:
    # tag the docker images
    - docker tag subt/ugv:ros $BASESTATION_REGISTRY/subt-ugv-ros
    - docker tag subt/ugv:ppc $BASESTATION_REGISTRY/subt-ugv-ppc
    - docker tag subt/ugv:nuc $BASESTATION_REGISTRY/subt-ugv-nuc
    # push the docker images to the local registry
    - docker push $BASESTATION_REGISTRY/subt-ugv-ros
    - docker push $BASESTATION_REGISTRY/subt-ugv-ppc
    - docker push $BASESTATION_REGISTRY/subt-ugv-nuc

  # pull images from the docker registry
  # - pull:
  #   # pull the docker images from the laptop local registry
  #   - docker pull $AZURE_REGISTRY/subt-ugv-ros
  #   - docker pull $AZURE_REGISTRY/subt-ugv-ppc
  #   - docker pull $AZURE_REGISTRY/subt-ugv-nuc
  #   # tag the docker images
  #   - docker tag $AZURE_REGISTRY/subt-ugv-ros subt/ugv:ros
  #   - docker tag $AZURE_REGISTRY/subt-ugv-ppc subt/ugv:ppc
  #   - docker tag $AZURE_REGISTRY/subt-ugv-nuc subt/ugv:nuc