# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # push images to the local docker registry
    - push:
      # use default docker context
      - docker context use default
      # tag the docker images
      - docker tag subt/ugv:ros $AZURE_REGISTRY/subt-ugv-ros
      - docker tag subt/ugv:ppc $AZURE_REGISTRY/subt-ugv-ppc
      - docker tag subt/ugv:nuc $AZURE_REGISTRY/subt-ugv-nuc
      - docker tag subt/ugv:sim $AZURE_REGISTRY/subt-ugv-sim
      # push the docker images to the local registry
      - docker push $AZURE_REGISTRY/subt-ugv-ros
      - docker push $AZURE_REGISTRY/subt-ugv-ppc
      - docker push $AZURE_REGISTRY/subt-ugv-nuc
      - docker push $AZURE_REGISTRY/subt-ugv-sim
      # remove the azure docker images
      - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)

    # pull images from the docker registry
    - pull:
      # use default docker context
      - docker context use default
      # pull the docker images from the local registry
      - docker pull $AZURE_REGISTRY/subt-ugv-ros
      - docker pull $AZURE_REGISTRY/subt-ugv-ppc
      - docker pull $AZURE_REGISTRY/subt-ugv-nuc
      - docker pull $AZURE_REGISTRY/subt-ugv-sim
      # tag the docker images
      - docker tag $AZURE_REGISTRY/subt-ugv-ros subt/ugv:ros
      - docker tag $AZURE_REGISTRY/subt-ugv-ppc subt/ugv:ppc
      - docker tag $AZURE_REGISTRY/subt-ugv-nuc subt/ugv:nuc
      - docker tag $AZURE_REGISTRY/subt-ugv-sim subt/ugv:sim
      # remove the azure docker images
      - docker rmi $(docker images | grep $AZURE_REGISTRY | tr -s ' ' | cut -d ' ' -f 1)
      # show the docker images
      - docker images
