####################################################################################################
- ssh:
  # access any intermediate server
  # - +ssh:{ ugv2:ugv2:/home/mtatum/.ssh/deploy }

  # setup scp
  - 'export username=ugv2'
  - 'export host=ugv2'
  
  - copy:
    # copy over ssh keys from local host to remote host  
    - ssh $username@$host 'mkdir -p ~/.ssh/'
    - scp -r /home/$USER/.ssh/deploy $username@$host:/home/$username/.ssh/
    - scp -r /home/$USER/.ssh/deploy.pub $username@$host:/home/$username/.ssh/
  - delete:
    - ssh $username@$host 'rm -rf ~/.ssh/deploy'
    - ssh $username@$host 'rm -rf ~/.ssh/deploy.pub'
  
####################################################################################################    
- x86.docker:
  ##################################################################################################
  # access any intermediate server
  # - +ssh:{ ugv2:ugv2:/home/mtatum/.ssh/deploy }

  # setup scp
  - 'export username=nvidia'
  - 'export host=xavier'

  ##################################################################################################
  - install:
    # TODO: needs to have 'login as root' option
    - apt-get update
    - apt install -y curl apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install docker-ce -y
    - usermod -a -G docker developer
  - check:
    - docker -v
    - docker run hello-world
  - uninstall:
    - apt-get remove docker docker-engine docker.io

####################################################################################################
- x86.nvidia-docker:
  ##################################################################################################
  # ssh into the remote robot
  # - +ssh:root:192.168.188.49
  - +ssh:developer:192.168.188.49:/home/katarina/.ssh/subt-vm/id_rsa
  - hostname
  - whoami
  - pwd
  - 'export DEPLOY_PATH=/home/$USER/deploy_ws/src/'
  ##################################################################################################
  - install:
    - docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
    - curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
    - distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    - curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
    - apt-get update
    - apt-get install -y nvidia-docker2
    - service docker restart
  - check:
    - nvidia-docker -v
    - docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
  - uninstall:
    - apt-get purge -y nvidia-docker

