# ////////////////////////////////////////////////////////////////////////////
- subt:
  - basestation:
# ////////////////////////////////////////////////////////////////////////////    
    - pwd
    - ls -all
    - cd $SUBT_PATH/
    - pwd

    # ////////////////////////////////////////////////////////////////////////////
    # perform all tasks that involve 'building'
    - build:
    # ////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common/
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile set ${deploybook_build_param}
        - catkin build --force-cmake
      - basestation:
        - cd basestation/
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile set ${deploybook_build_param}
        - catkin build --force-cmake
      # TODO:
      # - launch:
      #   - cd $DEPLOY_SRC/operations/launch/
      #   - rm -f .catkin_tools/profiles/profiles.yaml
      #   - catkin profile set ${computer_type_t}-basestation
      #   - catkin build --force-cmake
      #   - catkin clean -b --yes

    # ////////////////////////////////////////////////////////////////////////////
    # perform all tasks that involves 'launch'
    - launch:
    # ////////////////////////////////////////////////////////////////////////////
      - export launch_prefix="basestation"

      # //////////////////////////////////////////////////////////////////////////
      - start:
      # //////////////////////////////////////////////////////////////////////////
        - roscore:
          # start the tmux session
          - tmux new -s roscore -d
          # launch
          - tmux send -t roscore 'roscore' ENTER

        - gui:
          # start the tmux session
          - tmux new -s gui -d
          # launch
          - tmux send -t gui 'mon launch launch_subt ${launch_prefix}_gui.launch' ENTER

        - rosbag:
          # start the tmux session
          - tmux new -s rosbag -d
          # launch
          - tmux send -t rosbag 'cd $DEPLOY_SRC/operations/launch/ugv_setup/logging/base_station/scripts && ./basestation.bash' ENTER
          
        - relay_ugv1_agg:
          - tmux new -s relay_ugv1_agg -d
          - tmux send -t relay_ugv1_agg 'rosrun topic_tools relay /cm_rel/ugv1/bs/diagnostics_agg /diagnostics_agg' ENTER

        - relay_ugv2_agg:
          - tmux new -s relay_ugv2_agg -d
          - tmux send -t relay_ugv2_agg 'rosrun topic_tools relay /cm_rel/ugv2/bs/diagnostics_agg /diagnostics_agg' ENTER

      # //////////////////////////////////////////////////////////////////////////
      - stop:
      # //////////////////////////////////////////////////////////////////////////
        - rosbag:
          - stop:
            # start stop record
            - tmux new -s launch_rosbag_stop -d
            - tmux send -t launch_rosbag_stop 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER  
            # stop record node
            - tmux send -t launch_rosbag_stop 'rosnode kill /rosbag_recording_base_station' ENTER
            - sleep 3
          - sessions:
            # stop the sessions
            # - until rostopic list ; do sleep 1; done
            - tmux kill-session -t launch_rosbag_stop
            - tmux kill-session -t launch_rosbag
        - roscore:
          - tmux kill-session -t roscore
        - gui:
          - tmux kill-session -t gui
        - relay_ugv1_agg:
          - tmux kill-session -t relay_ugv1_agg
        - relay_ugv2_agg:
          - tmux kill-session -t relay_ugv2_agg
        