###################################################################################################
# setup the transfer
- hostname
- pwd
- 'export LOCAL_DEPLOY_PATH=$PWD/'
- 'export YELLOW="\033[1;33m"'
- 'export BLUE="\033[1;36m"'

####################################################################################################
- robot:
####################################################################################################
  # == user can modify ==
  - 'export host=192.168.188.49'
  - 'export user=developer'
  - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/src'
  - 'export copy_opts="-avzh -e \"ssh -i $HOME/.ssh/subt-vm/id_rsa\" "'

  ####################################################
  # perform actual transfer. do not change.
  ####################################################
  - print:
    # print
    - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
    - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
    - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
    - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
    # - ping -c 3 $host
  # transfer TO remote host
  - to:
      # print
      - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
      - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
      # create the remote directory
      # only works if ssh keys are setup
      - ssh $user@$host -i $HOME/.ssh/subt-vm/id_rsa "mkdir -p $REMOTE_DEPLOY_PATH"
      # copy command
      - export copy_cmd="rsync $copy_opts $LOCAL_DEPLOY_PATH $user@$host:$REMOTE_DEPLOY_PATH"
      - echo -e "\n${YELLOW}\t == TRANSFER == \n"
      - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
      - eval $copy_cmd
  # transfer FROM remote host
  - from:
      # print
      - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
      - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
      # create the remote directory
      - ssh $user@$host "mkdir -p $REMOTE_DEPLOY_PATH"
      # copy command
      - export copy_cmd="rsync $copy_opts $$user@$host:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH "
      - echo -e "\n${YELLOW}\t == TRANSFER == \n"
      - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
      - eval $copy_cmd
  # delete from remote host
  - delete:
    - ssh $user@$host "rm -rf $REMOTE_DEPLOY_PATH"
