# //////////////////////////////////////////////////////////////////////////////
- desktop:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario desktop-ugv"'
  # source the scenario file
  - source operations/deploy/scenarios/desktop-ugv.env

  # catkin profile for all workspace
  - export deploybook_catkin_profile=ugv

  # == extend all the computers that run on a ugv ==
  - ugv:
    # planning-pc
    - export deploybook_robot=desktop.ppc
    - +extend: robot/ugv/compose/ppc

    # nuc
    - export deploybook_robot=desktop.nuc
    - +extend: robot/ugv/compose/nuc

    # nuc
    - export deploybook_robot=desktop.sim
    - +extend: robot/ugv/compose/sim

# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the base scenario file
  - source operations/deploy/scenarios/.base.env

  # ////////////////////////////////////////////////////////////////////////////
  - ugv1:
  # ////////////////////////////////////////////////////////////////////////////

    # scenario file
    - 'export scenario=" --scenario azure/ugv1"'
    # source the scenario file
    - source operations/deploy/scenarios/azure/ugv1.env
    # type of catkin workspace to export
    - export deploybook_catkin_profile=ugv

    # extend all the computers that run on a ugv
    - export ssh_config=azure.ugv1
    - +extend: robot/ugv/transfer/vm-ugv
    
    - vm:
      # go to the remote computer, execute the steps
      # bug: make it use env variable
      - +ssh:{ subt:azure-ugv1:/home/$USER/.ssh/azure_vpn }

      - export deploybook_robot=desktop.ppc
      - +extend: robot/ugv/compose/ppc

      - export deploybook_robot=desktop.nuc
      - +extend: robot/ugv/compose/nuc

      - export deploybook_robot=desktop.sim
      - +extend: robot/ugv/compose/sim

  # ////////////////////////////////////////////////////////////////////////////
  - ugv2:
  # ////////////////////////////////////////////////////////////////////////////
    # scenario file
    - 'export scenario=" --scenario azure/ugv2"'
    # source the scenario file
    - source operations/deploy/scenarios/azure/ugv2.env
    # type of catkin workspace to export
    - export deploybook_catkin_profile=ugv

    # extend all the computers that run on a ugv
    - +extend: robot/ugv/transfer/vm-ugv
    
    - vm:
      # go to the remote computer, execute the steps
      # bug: make it use env variable
      - +ssh:{ subt:azure-ugv2:/home/$USER/.ssh/azure_vpn }

      # planning-pc
      - export deploybook_robot=desktop.ppc
      - +extend: robot/ugv/compose/ppc

      - export deploybook_robot=desktop.nuc
      - +extend: robot/ugv/compose/nuc

      - export deploybook_robot=desktop.sim
      - +extend: robot/ugv/compose/sim
  
  # ////////////////////////////////////////////////////////////////////////////
  - ugv3:
  # ////////////////////////////////////////////////////////////////////////////
    # scenario file
    - 'export scenario=" --scenario azure/ugv3"'
    # source the scenario file
    - source operations/deploy/scenarios/azure/ugv3.env
    # type of catkin workspace to export
    - export deploybook_catkin_profile=ugv

    # extend all the computers that run on a ugv
    - +extend: robot/ugv/transfer/vm-ugv
    
    - vm:
      # go to the remote computer, execute the steps
      # bug: make it use env variable
      - +ssh:{ subt:azure-ugv3:/home/$USER/.ssh/azure_vpn }

      # planning-pc
      - export deploybook_robot=desktop.ppc
      - +extend: robot/ugv/compose/ppc

      - export deploybook_robot=desktop.nuc
      - +extend: robot/ugv/compose/nuc

      - export deploybook_robot=desktop.sim
      - +extend: robot/ugv/compose/sim
  
# //////////////////////////////////////////////////////////////////////////////
- robots:
# //////////////////////////////////////////////////////////////////////////////
  # TODO: need to actually test the deploy on robot
  
  # ////////////////////////////////////////////////////////////////////////////
  - ugv1:
  # ////////////////////////////////////////////////////////////////////////////

    # scenario file
    - 'export scenario=" --scenario robot/ugv1"'
    # source the scenario file
    - source operations/deploy/scenarios/robot/ugv1.env

    # type of catkin workspace to export
    - 'export deploybook_catkin_profile="ugv"'

    # extend all the computers that run on a ugv
    - +extend: robot/ugv/transfer/ppc
    - +extend: robot/ugv/transfer/nuc
    - +extend: robot/ugv/transfer/xavier

    # == extend all the computers that run on a ugv ==
    - ugv:
      # go to the remote computer, execute the steps
      # bug: make it use env variable
      - +ssh:{ ugv1:ugv1:/home/$USER/.ssh/ugv/example_id_rsa }
    
      # planning-pc
      - export deploybook_robot=ugv.ppc
      - +extend: robot/ugv/compose/ppc

      # nuc
      - export deploybook_robot=ugv.nuc
      - +extend: robot/ugv/compose/nuc

      # # xavier
      # - export deploybook_robot=ugv.xavier
      # - +extend: robot/ugv/compose/xavier
