# export robot & build types
- 'export robot_type=ugv'
- 'export profile_type_t=ugv'

# //////////////////////////////////////////////////////////////////////////////
- r1:
# //////////////////////////////////////////////////////////////////////////////
  # compose environment scenario
  - 'export scenario=" --scenario r1"'
  
  # extend all the computers that run on a ugv
  - +extend: robot/ugv/computers

