# //////////////////////////////////////////////////////////////////////////////
- desktop:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario desktop-ugv"'
  # source the scenario file
  - source operations/deploy/scenarios/desktop-ugv.env

  # catkin profile for all workspace
  - export deploybook_catkin_profile=ugv

  # == extend all the computers that run on a ugv ==
  - ugv:
    # planning-pc
    - export deploybook_robot=desktop.ppc
    - +extend: robot/ugv/compose/ppc

    # nuc
    - export deploybook_robot=desktop.nuc
    - +extend: robot/ugv/compose/nuc

# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario azure-ugv"'
  # source the scenario file
  - source operations/deploy/scenarios/azure-ugv.env
  # type of catkin workspace to export
  - export deploybook_catkin_profile=ugv

  # extend all the computers that run on a ugv
  - +extend: robot/ugv/transfer/ugv

  # == extend all the computers that run on a ugv ==
  - ugv:
    # go to the remote computer, execute the steps
    # bug: make it use env variable
    - +ssh:{ kat:azure-ugv:/home/$USER/.ssh/azure/vm-keys/example_id_rsa }

    # planning-pc
    - export deploybook_robot=desktop.ppc
    - +extend: robot/ugv/compose/ppc

    - export deploybook_robot=desktop.nuc
    - +extend: robot/ugv/compose/nuc
  
# //////////////////////////////////////////////////////////////////////////////
- r1:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario azure-ugv"'
  # source the scenario file
  - source operations/deploy/scenarios/azure-ugv.env

  # type of catkin workspace to export
  - 'export deploybook_catkin_profile="ugv"'

  # extend all the computers that run on a ugv
  - +extend: robot/ugv/transfer/ppc
  - +extend: robot/ugv/transfer/nuc
  - +extend: robot/ugv/transfer/xavier

  # == extend all the computers that run on a ugv ==
  - ugv:
    # go to the remote computer, execute the steps
    # bug: make it use env variable
    - +ssh:{ ugv1:ugv1:/home/$USER/.ssh/ugv/example_id_rsa }
  
    # planning-pc
    - export deploybook_robot=ugv.ppc
    - +extend: robot/ugv/compose/ppc

    # nuc
    - export deploybook_robot=ugv.nuc
    - +extend: robot/ugv/compose/nuc

    # # xavier
    # - export deploybook_robot=ugv.xavier
    # - +extend: robot/ugv/compose/xavier
