# //////////////////////////////////////////////////////////////////////////////
- desktop:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario desktop-r1"'
  
  # type of catkin workspace to export
  - 'export deploybook_catkin_profile="ugv"'

  # == extend all the computers that run on a ugv ==

  # planning-pc
  - export deploybook_robot=desktop.ppc
  - +extend: robot/ugv/compose/ppc

  # nuc
  - export deploybook_robot=desktop.nuc
  - +extend: robot/ugv/compose/nuc

# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////
  # scenario file
  - 'export scenario=" --scenario azure-r1"'

  # type of catkin workspace to export
  - 'export deploybook_catkin_profile="ugv"'

  # TODO: move to scenario file
  # azure computer setup
  - 'export user=kat'
  - 'export host=azure-r1'

  # extend all the computers that run on a ugv
  # - +extend: robot/ugv/transfer

  # go to the remote computer, execute the steps
  # bug: make it use env variable
  - +ssh:{ kat:azure-r1:/home/$USER/.ssh/azure/vm-keys/example_id_rsa }

  # == extend all the computers that run on a ugv ==

  # planning-pc
  - export deploybook_robot=desktop.ppc
  - +extend: robot/ugv/compose/ppc

  # nuc
  - export deploybook_robot=desktop.nuc
  - +extend: robot/ugv/compose/nuc
  
# //////////////////////////////////////////////////////////////////////////////
- r1:
# //////////////////////////////////////////////////////////////////////////////
  # compose environment scenario
  - 'export scenario=" --scenario r1"'

  # extend all the computers that run on a ugv
  # - +extend: robot/ugv/transfer

  # go to the remote computer, execute the steps
  # bug: make it use env variable
  - +ssh:{ subt:ugv1:/home/$USER/.ssh/deploy }
  
  # extend all the computers that run on a ugv
  - +extend: robot/ugv/compose/ppc
  # - +extend: robot/ugv/compose/nuc
  # - +extend: robot/ugv/compose/xavier

