####################################################################################################
# robot 1 configuration file
- r1:
####################################################################################################

  ##################################################################################################
  - xavier:
  ##################################################################################################
    - 'export YELLOW="\033[1;33m"'
    - 'export BLUE="\033[1;36m"'

    ################################################################################################
    # copy deploy repo from basestation to r1.nuc
    - transfer:
    ################################################################################################
      
      ### == user can modify ==
      
      # connections
      - 'export user=nvidia'
      - 'export host=xavier'
      - 'export HOP_HOST=robot@planning-pc'
      
      # paths
      - 'export LOCAL_DEPLOY_PATH=/home/$USER/deploy_ws/src'
      - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/'
      
      # rsync options
      - 'export copy_opts="-avzh --exclude=src/planning" '
      - export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH -e 'ssh $HOP_HOST ssh ' $user@$host:$REMOTE_DEPLOY_PATH "
      - export copy_from="rsync $copy_opts --exclude 'src/planning' $user@$host:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH "

      ### == user can modify done. ==

      ####################################################
      # perform actual transfer. do not change.
      ####################################################
      - print:
        # print
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
        - echo -e "\n${YELLOW}\t transfer to -> \t $copy_to \n" ;

      - transfer:
        - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
        - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
        - echo -e "\n${YELLOW}\t username -> \t $user \n" ;

        # transfer TO remote host
        - to:
          # create the remote directory
          - ssh $HOP_HOST ssh $user@$host "mkdir -p $REMOTE_DEPLOY_PATH"
          
          # copy command
          - 'export copy_cmd=$copy_to'

        # transfer FROM remote host
        - from:
          - 'export copy_cmd=$copy_from'

        # evaluate copy
        - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
        - eval $copy_cmd
      
      # delete remote deploy workspace
      - delete:
        - ssh $user@$host "rm -rf $REMOTE_DEPLOY_PATH"

    ################################################################################################
    - docker:
    ################################################################################################
      ####################################################
      # ssh into the remote robot
      ####################################################
      - +ssh:{robot:planning-pc:/home/$USER/.ssh/planning_pc }
      - +ssh:{nvidia:xavier:/home/nvidia/.ssh/nuc }
      
      ####################################################
      # setup
      ####################################################
      - hostname
      - whoami
      - pwd
      
      ####################################################
      # path setup
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src/'

      - 'export DOCKER_CONFIG=subt/subt'
      - 'export DOCKER_CONFIG_PATH=docker/env'
      
      ####################################################
      # print docker configuration information
      ####################################################
      - print.build:
        - echo -e "\n${BLUE} == Docker images to create == \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/osrf.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/ros.config \n" ;
        - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/field/r1/xavier.config \n" ;
        - echo -e "\n${YELLOW} ** Remember to always transfer any changed configuration files! ** \n";
      - print.run:
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG \n" ;
        - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG_PATH/subt/subt.config \n" ;
        - echo -e "\n${YELLOW}\t subt remote env filepath -> \t $DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config \n"
        - while IFS= read line;
          do 
            echo -e ${BLUE} "\t$line";
          done < "$DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config"

      ####################################################
      # build docker images
      ####################################################
      - cd $DEPLOY_SRC/docker/scripts
      - image:
        - 'export BUILD_ARGS="--force" '
        - osrf:
          - echo $LANG
          - ./build.bash --env local/osrf/ros $BUILD_ARGS
          - ./build.bash --env local/osrf/osrf $BUILD_ARGS
        - subt:
          - ./build.bash --env local/subt/ros $BUILD_ARGS
          - ./build.bash --env field/r1/xavier $BUILD_ARGS

      ####################################################
      # start docker images
      ####################################################
      - start:
        - 'export START_ARGS=" --no-nvidia " '
        - ./run.bash --env field/r1/xavier $START_ARGS

      ####################################################
      # stop docker images
      ####################################################
      - stop:
        - 'export STOP_ARGS="--stop --containers " '
        - ./clean.bash --env field/r1/xavier $STOP_ARGS
      
      - remove:
        - 'export STOP_ARGS="--remove --containers " '
        - ./clean.bash --env field/r1/xavier $STOP_ARGS
      
      ####################################################
      # delete docker images & corresponding containers
      ####################################################
      - clean:
        - 'export DELETE_ARGS="--containers" '
        - ./clean.bash --env field/r1/xavier $DELETE_ARGS
        - ./clean.bash --env local/subt/ros $DELETE_ARGS
        - ./clean.bash --env local/osrf/osrf $DELETE_ARGS
        - ./clean.bash --env local/osrf/ros $DELETE_ARGS
      
      ####################################################
      # misc.
      ####################################################
      - dangling:
        - docker rmi -f $(docker images -f "dangling=true" -q)
      
    ################################################################################################
    - deploy:
    ################################################################################################
      - +ssh:{robot:planning-pc:/home/$USER/.ssh/planning_pc }
      - +ssh:{nvidia:xavier:/home/nvidia/.ssh/nuc }
      # - +docker:subt  # no docker in xavier
      
      - hostname
      - whoami
      - pwd
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src'
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - cd $DEPLOY_SRC
      - pwd

      ####################################################
      # clone workspaces
      ####################################################
      - clone:
    
        # clone & update the perception workspace
        - cd perception/

        # update the git submodule
        - submodule:
          - cd object_detection
          - git submodule init
          - git submodule update --recursive
        
        - rosdep:
          - deps:
            - source /opt/ros/melodic/setup.bash
            - cd deps/catkin
            - rosdep install --from-paths . --ignore-src --rosdistro melodic -y
          - perception:
            - source ../../devel/perception/deps/setup.bash
            - rosdep install --from-paths . --ignore-src --rosdistro melodic -y

      ####################################################
      # build workspaces
      ####################################################
      - build:
        - cd perception/
        
        # build the deps workspaces
        - deps:
          - cd deps/catkin
          - catkin build
        
        # build perception workspace
        - perception:
          - catkin build

        # build launch workspace
        - launch:
          - cd $DEPLOY_SRC/launch/
          - catkin config --extend ../../devel/perception/repo
          - catkin build

      ####################################################
      # clean workspaces
      ####################################################
      - clean:
        - cd perception/
        - launch:
          - cd $DEPLOY_SRC/launch/
          - catkin profile set perception
          - catkin clean -y
        - repo:
          - catkin clean -y
        - deps:
          - cd deps/catkin
          - catkin clean -y

      ####################################################
      # launch workspaces
      ####################################################
      - launch:
        ### == user can modify ==
        
        # launch configuration variables
        - 'export host=$(hostname)'
        - 'export config=ugv1'
        - 'export MCAST_GROUP=224.0.0.251'
        - 'export UGV_XAVIER=true'

        ### == user can modify done. ==

        # read the launch configuration params
        - export config_data=""
        - export CONFIG_FILE="$DEPLOY_SRC/launch/robot_launch_scripting/config/${config}.config"
        - while IFS='' read -r line || [[ -n "$line" ]]; do
            if [ ! "${line:0:1}" == "#" ]; then
              config_data="$line ";
            fi
          done < "$CONFIG_FILE";
        - echo ${config_data}

        - start:
          - roscore:
            # enable roscore
            - 'export ROS_MASTER=true'
            # start the tmux sessions
            - tmux new -s ${host}_check_roscore -d
            # source
            - tmux send -t ${host}_check_roscore 'source $DEPLOY_WS/devel/perception/launch/setup.bash' ENTER
            # run roscore
            - tmux send -t ${host}_check_roscore 'rosrun robot_launch_scripting launch_roscore.sh' ENTER
            
          - perception:
            # start the tmux session
            - tmux new -s ${host}_launch_${config} -d
            # source
            - tmux send -t ${host}_launch_${config} 'source $DEPLOY_WS/devel/perception/launch/setup.bash' ENTER
            # run perception-pc launch
            - tmux send -t ${host}_launch_${config} 'mon launch robot_launch_scripting ugv_config.launch ${config_data}' ENTER
            # message user
            - echo "Launch deployed in tmux session ${host}_launch_${config}"

        - stop:
          # remove all the tmux sessions
          - perception:
            - tmux kill-session -t ${host}_launch_${config}
          - roscore:  
            - tmux kill-session -t ${host}_check_roscore
          
        - rosclean:
          # stop all ros nodes
          - source $DEPLOY_WS/devel/perception/repo/setup.bash
          - ps aux | grep ros
          - rosnode kill -a
          - pkill -f ros
          - rosnode list
          - ps aux | grep ros
      