####################################################################################################
# robot 1 configuration file
- r1:
####################################################################################################

  ##################################################################################################
  - xavier:
  ##################################################################################################
    - 'export YELLOW="\033[1;33m"'
    - 'export BLUE="\033[1;36m"'

    ################################################################################################
    - deploy:
    ################################################################################################
      - +ssh:{robot:planning-pc:/home/$USER/.ssh/planning_pc }
      - +ssh:{nvidia:xavier:/home/nvidia/.ssh/nuc }
      
      - hostname
      - whoami
      - pwd
      - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src'
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - cd $DEPLOY_SRC
      - pwd

      ####################################################
      # build workspaces
      ####################################################
      - build:
        - cd perception/
        
        # build the deps workspaces
        - deps:
          - cd deps/catkin
          - catkin build
        
        # build perception workspace
        - perception:
          - catkin build

        # build launch workspace
        - launch:
          - cd $DEPLOY_SRC/launch/
          - catkin config --extend ../../devel/perception/repo
          - catkin build

      ####################################################
      # clean workspaces
      ####################################################
      - clean:
        - cd perception/
        - launch:
          - cd $DEPLOY_SRC/launch/
          - catkin profile set perception
          - catkin clean -y
        - repo:
          - catkin clean -y
        - deps:
          - cd deps/catkin
          - catkin clean -y

      ####################################################
      # launch workspaces
      ####################################################      
      - launch:
        ### == user can modify ==

        # launch configuration variables
        - 'export host=$(hostname)'
        - 'export MCAST_GROUP=224.0.0.251'
        - 'export ROBOT_NAME=ugv1'
        - 'export USER=nvidia'
        - 'export ROS_MASTER_URI=http://planning-pc:11311'
        - 'export ROS_HOSTNAME=xavier'
        - 'export ROS_MASTER=false'

        ### == user can modify done. ==
        - start:
          - perception:
            # start the tmux session
            - tmux new -s launch_perception -d
            # export path
            - tmux send -t launch_perception 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/' ENTER
            # source
            - tmux send -t launch_perception 'source $DEPLOY_WS/devel/perception/launch/setup.zsh' ENTER
            # run perception-pc launch
            - tmux send -t launch_perception 'mon launch robot_launch_scripting subt.launch robot:=robots/xavier' ENTER
            # message user
            - echo "Launch deployed in tmux session launch_perception"

        - stop:
          # remove all the tmux sessions
          - perception:
            - tmux kill-session -t launch_perception

        - rosclean:
          # stop all ros nodes
          - source $DEPLOY_WS/devel/perception/repo/setup.bash
          - ps aux | grep ros
          - rosnode kill -a
          - pkill -f ros
          - rosnode list
          - ps aux | grep ros
      