##################################################################################################
- old-basestation:
##################################################################################################
  - 'export YELLOW="\033[1;33m"'
  - 'export BLUE="\033[1;36m"'
  - 'export RESET="\033[0m"'

  ################################################################################################
  # copy deploy repo from basestation to old-basestation
  - transfer:
  ################################################################################################
    
    ### == user can modify ==
    # testing setp

    # connections
    - 'export host=basestation-pc'
    - 'export user=mtatum'

    # paths
    - 'export LOCAL_DEPLOY_PATH=/home/$USER/deploy_ws/src'
    - 'export REMOTE_DEPLOY_PATH=/home/$user/deploy_ws/'
    
    # rsync options
    - 'export copy_opts="
        -avzh
        --delete
        --exclude=src/launch/ugv_setup/logging/base_station/bags
        -e \"ssh -i $HOME/.ssh/deploy\" " ' 
    # rsync commands
    - export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH $user@$host:$REMOTE_DEPLOY_PATH "
    - export copy_from="rsync $copy_opts $user@$host:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH "

    ### == user can modify done. ==

    ####################################################
    # perform actual transfer. do not change.
    ####################################################
    - print:
      # print
      - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
      - echo -e "\n${YELLOW}\t username -> \t $user \n" ;
      - echo -e "\n${YELLOW}\t transfer to -> \t $copy_to \n" ;

    - transfer:
      - echo -e "\n${YELLOW}\t local deploy path -> \t $LOCAL_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t remote deploy path -> \t $REMOTE_DEPLOY_PATH \n" ;
      - echo -e "\n${YELLOW}\t host -> \t $host \n" ;
      - echo -e "\n${YELLOW}\t username -> \t $user \n" ;

      # transfer TO remote host
      - to:
        # create the remote directory
        - ssh $user@$host -i ~/.ssh/deploy "mkdir -p $REMOTE_DEPLOY_PATH"

        # copy command
        - 'export copy_cmd=$copy_to'

      # transfer FROM remote host
      - from:
        - 'export copy_cmd=$copy_from'

      # evaluate copy
      - echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
      - eval $copy_cmd

  ################################################################################################
  - delete-bags:
  ################################################################################################
    - +ssh:{ mtatum:basestation-pc:/home/$USER/.ssh/deploy }
    - 'export DEPLOY_SRC=/home/$(whoami)/deploy_ws/src/'
    - rm -rf $DEPLOY_SRC/launch/ugv_setup/logging/base_station/bags/*