blacklist: []
build_space: ../../../../build/perception/recording
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
- -DCATKIN_ENABLE_TESTING=False
devel_layout: linked
devel_space: ../../../../devel/perception/recording
extend_path: ../../../../devel/perception/repo
install: false
install_space: ../../../../install/perception/recording
isolate_install: false
jobs_args: []
log_space: ../../../../logs
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
