blacklist: [ ueye_cam ]
build_space: ../../../../build/perception/deps
catkin_make_args: []
cmake_args:
  - -DCMAKE_BUILD_TYPE=Release
  - -DPYTHON_EXECUTABLE=/usr/bin/python3.6
  - -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m
  - -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so
devel_layout: linked
devel_space: ../../../../devel/perception/deps
extend_path: ../../../../devel/perception/common
install: false
install_space: ../../../../install/perception/deps
isolate_install: false
jobs_args: []
log_space: ../../../../logs/perception/deps
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
