# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/azure/.azure.env

  - uav:

    # azure docker registry
    - +extend: systems/azure/uav/vm/registry

  # ////////////////////////////////////////////////////////////////////////////
  - uav1:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav1
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - +extend: common/skel_t
      - compose:
        - +ssh:{ azure.uav1 }
        - +extend: systems/azure/uav/vm/compose
      - catkin:
        - +ssh:{ azure.uav1 }
        - +docker:uav-sim-shell
        - +extend: systems/azure/uav/vm/catkin
      - teamviewer:
        - +ssh:{ azure.uav1 }
        - sudo teamviewer info | grep " ID:"

  # ////////////////////////////////////////////////////////////////////////////
  - uav2:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav2
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - +extend: common/skel_t
      - compose:
        - +ssh:{ azure.uav2 }
        - +extend: systems/azure/uav/vm/compose
      - catkin:
        - +ssh:{ azure.uav2 }
        - +docker:uav-sim-shell
        - +extend: systems/azure/uav/vm/catkin
      - teamviewer:
        - +ssh:{ azure.uav2 }
        - sudo teamviewer info | grep " ID:"


  # ////////////////////////////////////////////////////////////////////////////
  - uav3:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav3
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - +extend: common/skel_t
      - compose:
        - +ssh:{ azure.uav3 }
        - +extend: systems/azure/uav/vm/compose
      - catkin:
        - +ssh:{ azure.uav3 }
        - +docker:uav-sim-shell
        - +extend: systems/azure/uav/vm/catkin
      - teamviewer:
        - +ssh:{ azure.uav3 }
        - sudo teamviewer info | grep " ID:"


  # ////////////////////////////////////////////////////////////////////////////
  - uav4:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav4
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - +extend: common/skel_t
      - compose:
        - +ssh:{ azure.uav4 }
        - +extend: systems/azure/uav/vm/compose
      - catkin:
        - +ssh:{ azure.uav4 }
        - +docker:uav-sim-shell
        - +extend: systems/azure/uav/vm/catkin
      - teamviewer:
        - +ssh:{ azure.uav4 }
        - sudo teamviewer info | grep " ID:"
