# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/azure/.azure.env

  # ////////////////////////////////////////////////////////////////////////////
  - uav1:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav1
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - compose:
        - +ssh:{ azure.uav1 }
        - +extend: systems/azure/uav/vm/compose

  # ////////////////////////////////////////////////////////////////////////////
  - uav2:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav2
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - compose:
        - +ssh:{ azure.uav2 }
        - +extend: systems/azure/uav/vm/compose


  # ////////////////////////////////////////////////////////////////////////////
  - uav3:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav3
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - compose:
        - +ssh:{ azure.uav3 }
        - +extend: systems/azure/uav/vm/compose


  # ////////////////////////////////////////////////////////////////////////////
  - uav4:
  # ////////////////////////////////////////////////////////////////////////////

    # source the computer-level scenario file
    - export filename=systems/azure/uav4
    - source operations/deploy/scenarios/$filename.env
    - export scenario=" --scenario $filename"

    - vm:
      - +extend: common/transfer
      - compose:
        - +ssh:{ azure.uav4 }
        - +extend: systems/azure/uav/vm/compose

