# //////////////////////////////////////////////////////////////////////////////
- azure:
# //////////////////////////////////////////////////////////////////////////////

  # source the top-level scenario files
  - source operations/deploy/scenarios/.base.env
  - source operations/deploy/scenarios/systems/azure/.azure.env

  # ////////////////////////////////////////////////////////////////////////////
  - uav:
  # ////////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - uav1:
    # ////////////////////////////////////////////////////////////////////////////

      # source the computer-level scenario file
      - export filename=systems/azure/uav1
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - vm:
        - +extend: common/transfer
        - +extend: common/skel_t
        - compose:
          - +ssh:{ azure.uav1 }
          - +extend: systems/azure/uav/vm/compose
        - catkin:
          - +ssh:{ azure.uav1 }
          - core:
            - +docker:uav-cpu-shell
            - +extend: systems/local/uav/vm/catkin-core
          - perception:
            - +docker:uav-perception-cpu-shell
            - +extend: systems/local/uav/vm/catkin-perception
        - teamviewer:
          - +ssh:{ azure.uav1 }
          - sudo teamviewer info | grep " ID:"
        - registry:
          - export DOCKER_CONTEXT=azure-uav1
          - +extend: systems/azure/uav/vm/registry

    # ////////////////////////////////////////////////////////////////////////////
    - uav2:
    # ////////////////////////////////////////////////////////////////////////////

      # source the computer-level scenario file
      - export filename=systems/azure/uav2
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - vm:
        - +extend: common/transfer
        - +extend: common/skel_t
        - compose:
          - +ssh:{ azure.uav2 }
          - +extend: systems/azure/uav/vm/compose
        - catkin:
          - +ssh:{ azure.uav2 }
          - core:
            - +docker:uav-cpu-shell
            - +extend: systems/local/uav/vm/catkin-core
          - perception:
            - +docker:uav-perception-cpu-shell
            - +extend: systems/local/uav/vm/catkin-perception
        - teamviewer:
          - +ssh:{ azure.uav2 }
          - sudo teamviewer info | grep " ID:"
        - registry:
          - export DOCKER_CONTEXT=azure-uav2
          - +extend: systems/azure/uav/vm/registry

    # ////////////////////////////////////////////////////////////////////////////
    - uav3:
    # ////////////////////////////////////////////////////////////////////////////

      # source the computer-level scenario file
      - export filename=systems/azure/uav3
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - vm:
        - +extend: common/transfer
        - +extend: common/skel_t
        - compose:
          - +ssh:{ azure.uav3 }
          - +extend: systems/azure/uav/vm/compose
        - catkin:
          - +ssh:{ azure.uav3 }
          - core:
            - +docker:uav-cpu-shell
            - +extend: systems/local/uav/vm/catkin-core
          - perception:
            - +docker:uav-perception-cpu-shell
            - +extend: systems/local/uav/vm/catkin-perception
        - teamviewer:
          - +ssh:{ azure.uav3 }
          - sudo teamviewer info | grep " ID:"
        - registry:
          - export DOCKER_CONTEXT=azure-uav3
          - +extend: systems/azure/uav/vm/registry

    # ////////////////////////////////////////////////////////////////////////////
    - uav4:
    # ////////////////////////////////////////////////////////////////////////////

      # source the computer-level scenario file
      - export filename=systems/azure/uav4
      - source operations/deploy/scenarios/$filename.env
      - export scenario=" --scenario $filename"

      - vm:
        - +extend: common/transfer
        - +extend: common/skel_t
        - compose:
          - +ssh:{ azure.uav4 }
          - +extend: systems/azure/uav/vm/compose
        - catkin:
          - +ssh:{ azure.uav4 }
          - core:
            - +docker:uav-cpu-shell
            - +extend: systems/local/uav/vm/catkin-core
          - perception:
            - +docker:uav-perception-cpu-shell
            - +extend: systems/local/uav/vm/catkin-perception
        - teamviewer:
          - +ssh:{ azure.uav4 }
          - sudo teamviewer info | grep " ID:"
        - registry:
          - export DOCKER_CONTEXT=azure-uav4
          - +extend: systems/azure/uav/vm/registry
