# ////////////////////////////////////////////////////////////////////////////
- workspace:
# ////////////////////////////////////////////////////////////////////////////

  - ppc:
    - cd $SUBT_PATH/
    - pwd
    - whoami

    # ////////////////////////////////////////////////////////////////////////////
    - clean:
    # ////////////////////////////////////////////////////////////////////////////
      - rm -rf ~/deploy_ws/devel/ugv/ppc
      - rm -rf ~/deploy_ws/build/ugv/ppc
      - rm -rf ~/deploy_ws/install/ugv/ppc
      - rm -rf ~/deploy_ws/logs/ugv/ppc

    # ////////////////////////////////////////////////////////////////////////////
    - build:
    # ////////////////////////////////////////////////////////////////////////////

      - common:
        - cd ~/deploy_ws/src/common
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-ppc
        - catkin config
        - catkin build --force-cmake

      - ugv:
        - cd ~/deploy_ws/src/ugv
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-ppc
        - catkin config
        - catkin build --force-cmake

      - uav:
        - cd ~/deploy_ws/src/uav
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-ppc
        - catkin config
        - catkin build --force-cmake

      - subt_launch:
        - cd ~/deploy_ws/src/subt_launch
        - rm -f .catkin_tools/profiles/profiles.yaml
        - catkin profile list
        - catkin profile set ugv-ppc
        - catkin config
        - catkin build --force-cmake
