# //////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - image:
  # ////////////////////////////////////////////////////////////////////////////
    - docker-compose-wrapper $scenario build ros-image
    - docker-compose-wrapper $scenario build ppc-image

  # ////////////////////////////////////////////////////////////////////////////
  - container:
  # ////////////////////////////////////////////////////////////////////////////
    - shell:
      # - docker-compose-wrapper $scenario -p ros-shell up --force-recreate -d ros-shell
      - docker-compose-wrapper $scenario -p ppc-shell up --force-recreate -d ppc-shell
      - docker-compose-wrapper $scenario -p vdb-shell up --force-recreate -d vdb-shell
    # stopping containers
    - stop:
      - docker stop $(docker ps -a -q)
    # removing containers
    - rm:
      - docker rm $(docker ps -a -q)
