# //////////////////////////////////////////////////////////////////////////////
- docker:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - registry:
  # ////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - azure:
    # //////////////////////////////////////////////////////////////////////////

      # pull images from the docker registry
      - pull:
        # change the docker context to the ugv azure docker daemon
        - docker context use $DOCKER_CONTEXT
        # pull the docker images from the laptop local registry
        - docker pull $AZURE_REGISTRY/subt-ugv-ros
        - docker pull $AZURE_REGISTRY/subt-ugv-ppc
        - docker pull $AZURE_REGISTRY/subt-ugv-nuc
        # tag the docker images
        - docker tag $AZURE_REGISTRY/subt-ugv-ros subt/ugv:ros
        - docker tag $AZURE_REGISTRY/subt-ugv-ppc subt/ugv:ppc
        - docker tag $AZURE_REGISTRY/subt-ugv-nuc subt/ugv:nuc
        # remove the docker docker registry images
        - docker rmi $AZURE_REGISTRY/subt-ugv-ros
        - docker rmi $AZURE_REGISTRY/subt-ugv-ppc
        - docker rmi $AZURE_REGISTRY/subt-ugv-nuc
        # show the docker images
        - docker images
        # change the docker context back to the default docker daemon
        - docker context use default

      # pull images from the docker registry
      # - push:
      #   # tag the docker images
      #   - docker tag subt/ugv:ros $ROBOT_REGISTRY/subt-ugv-ros
      #   - docker tag subt/ugv:ppc $ROBOT_REGISTRY/subt-ugv-ppc
      #   - docker tag subt/ugv:nuc $ROBOT_REGISTRY/subt-ugv-nuc
      #   # pull the docker images from the laptop local registry
      #   - docker push $ROBOT_REGISTRY/subt-ugv-ros
      #   - docker push $ROBOT_REGISTRY/subt-ugv-ppc
      #   - docker push $ROBOT_REGISTRY/subt-ugv-nuc
      #   # remove the docker docker registry images
      #   - docker rmi $ROBOT_REGISTRY/subt-ugv-ros
      #   - docker rmi $ROBOT_REGISTRY/subt-ugv-ppc
      #   - docker rmi $ROBOT_REGISTRY/subt-ugv-nuc

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////

      # pull images from the docker registry
      - pull:
        # tag the docker images on the basestation registry
        - docker tag subt/ugv:ros $BASESTATION_REGISTRY/subt-ugv-ros
        - docker tag subt/ugv:ppc $BASESTATION_REGISTRY/subt-ugv-ppc
        - docker tag subt/ugv:nuc $BASESTATION_REGISTRY/subt-ugv-nuc

        # change the docker context to the ugv azure docker daemon
        - docker context use $DOCKER_CONTEXT
        # pull the docker images from the laptop local registry
        - docker pull $BASESTATION_REGISTRY/subt-ugv-ros
        - docker pull $BASESTATION_REGISTRY/subt-ugv-ppc
        - docker pull $BASESTATION_REGISTRY/subt-ugv-nuc
        # tag the docker images
        - docker tag $BASESTATION_REGISTRY/subt-ugv-ros subt/ugv:ros
        - docker tag $BASESTATION_REGISTRY/subt-ugv-ppc subt/ugv:ppc
        - docker tag $BASESTATION_REGISTRY/subt-ugv-nuc subt/ugv:nuc
        # remove the docker docker registry images
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-ros
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-ppc
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-nuc
        # show the docker images
        - docker images
        # change the docker context back to the default docker daemon
        - docker context use default

        # remove the docker images on the basestation registry
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-ros
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-ppc
        - docker rmi $BASESTATION_REGISTRY/subt-ugv-nuc
