# export the local & remote paths
- export LOCAL_DEPLOY_PATH=/home/$USER/deploy_ws/src
- export REMOTE_DEPLOY_PATH=/home/$remote_username/deploy_ws/

# export local and remote workspaces
- 'export copy_opts="-avzh --delete
    --exclude=src/basestation
    --exclude=src/ugv/nuc
    --exclude=src/uav/
    --exclude=src/simulation/
    --exclude=src/perception/
    --exclude=*.git/
  " '

- to:
  # create the remote directory
  - ssh $deploy_ssh "mkdir -p $REMOTE_DEPLOY_PATH"

  # copy command
  - 'export copy_to="rsync $copy_opts $LOCAL_DEPLOY_PATH $deploy_ssh:$REMOTE_DEPLOY_PATH "'
  - 'export copy_cmd=$copy_to'

- from:
  # copy command
  - 'export copy_from="rsync $copy_opts $deploy_ssh:$REMOTE_DEPLOY_PATH $LOCAL_DEPLOY_PATH"'
  - 'export copy_cmd=$copy_from'

# evaluate the copy command
- echo -e "\n${YELLOW}\t copy command -> \t $copy_cmd \n"
- eval $copy_cmd
