- ugv:
    # ROS packages for ugv[nuc] install
    common:
      apt:
        - python2.7
        - python-setuptools
        - python-pip
        - python-requests
        - build-essential
        - cmake
        - cppcheck
        - gdb
        - git
        - lsb-release
        - software-properties-common
        - sudo
        - vim
        - nano
        - emacs
        - wget
        - curl
        - less
        - net-tools
        - tmux
        - byobu
        - iputils-ping
        - xvfb
        - locales
        - tzdata
        - debian-archive-keyring
        - apt-transport-https
        - git-lfs
        - freerdp-x11
        - zsh
        - lm-sensors
        - tmuxp
        # azure cli
        - ca-certificates
        - curl
        - htop
        - traceroute
        - iftop
      pip:
        - tmuxp
    ppc:
      - libboost-all-dev
      - libeigen3-dev
      - assimp-utils
      - libcgal-dev
      - libcgal-qt5-dev
      - libproj-dev
      - libnlopt-dev
      - python-wstool
      - python-catkin-tools
      - libglfw3-dev
      - libblosc-dev
      - libopenexr-dev
      - liblog4cplus-dev
      - libsuitesparse-dev
      - libsdl1.2-dev
      - libncurses5-dev
      - graphviz
      - doxygen
      - sharutils
      - ros-melodic-smach-viewer
      - ros-melodic-tf-conversions
      - ros-melodic-random-numbers
      - ros-melodic-ros-type-introspection
      - ros-melodic-pcl-ros
      - ros-melodic-rosfmt
      - ros-melodic-rosserial
      - ros-melodic-serial
    nuc:
      - libboost-all-dev
      - libeigen3-dev
      - assimp-utils
      - libcgal-dev
      - libcgal-qt5-dev
      - libproj-dev
      - libnlopt-dev
      - python-wstool
      - python-catkin-tools
      - libglfw3-dev
      - libblosc-dev
      - libopenexr-dev
      - liblog4cplus-dev
      - libsuitesparse-dev
      - libsdl1.2-dev
      - libncurses5-dev
      - libpcap-dev
      - graphviz
      - doxygen
      - sharutils
      - ros-melodic-smach-viewer
      - ros-melodic-tf-conversions
      - ros-melodic-random-numbers
      - ros-melodic-ros-type-introspection
      - ros-melodic-pcl-ros
      - ros-melodic-rosfmt
      - ros-melodic-rosserial
      - ros-melodic-serial
