
# //////////////////////////////////////////////////////////////////////////////
# User Defined Variables
# USER INPUT ALLOWED HERE
#   - please change any variables to match your system
# //////////////////////////////////////////////////////////////////////////////

# enable if you wish to install nvidia-docker on your localhost
# - this 'flag' allows for the 'nvidia-docker' install
localhost_nvidia_docker: true

# enable if you wish to install ROS [melodic] on your localhost
localhost_ros: true
