# //////////////////////////////////////////////////////////////////////////////
# update all the deploy repo git submodules
# //////////////////////////////////////////////////////////////////////////////

- pwd

# //////////////////////////////////////////////////////////////////////////////
- submodule:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - clean:
  # ////////////////////////////////////////////////////////////////////////////

    # clean for the different system prefixes
    - localhost:
      - +extend: common/git/clean
    - basestation:
      - system76:
        - +extend: common/git/clean
      - laptop:
          - +extend: common/git/clean

    # remove untracked files
    - git clean -xfd
    # remove unstaged changes
    - git checkout -- .
    # remove untracked files in all submodules
    - if [ ! -z "$(ls .)" ]; then git submodule foreach --recursive git clean -xfd; fi
    # reset top level
    # - git reset --hard
    # reset the submodules, recursive
    # - git submodule foreach --recursive git reset --hard
    # - git submodule update --init --recursive
    # show the git status
    - pwd
    - if [ ! -z "$(ls .)" ]; then git status; fi

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to where the HEAD in the intermediate repo is set to.
  - clone:
  # ////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - localhost:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/clone/clone.base
      - +extend: common/git/clone/clone.simulation
      - +extend: common/git/clone/clone.ugv
      - +extend: common/git/clone/clone.uav

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////
      - system76:
        - +extend: common/git/clone/clone.base
        - +extend: common/git/clone/clone.ugv
        - +extend: common/git/clone/clone.ugv.hardware
        - +extend: common/git/clone/clone.uav
        - +extend: common/git/clone/clone.simulation

      - laptop:
        - +extend: common/git/clone/clone.base
        - +extend: common/git/clone/clone.uav
        - +extend: common/git/clone/clone.simulation

    # //////////////////////////////////////////////////////////////////////////
    - slam:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/clone/clone.ugv.slam
      - +extend: common/git/clone/clone.uav.slam

    # show the git status in the intermediate-repo
    - pwd
    - git status

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to what the branch in the intermediate repo is set to.
  - pull:
  # ////////////////////////////////////////////////////////////////////////
    - extras:
      - simulation:
        - cd simulation
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd subt_gazebo
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - uav:
        - cd uav
        - slam:
          - cd slam
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - ugv:
        - cd ugv
        - hardware:
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - slam:
          - devel:
            - cd slam/devel
            - git submodule update --init --recursive .
            - git clean -d -f -f
          - robot:
            - cd slam/robot
            - git submodule update --init --recursive .
            - git clean -d -f -f

    - base:
      - basestation:
        - cd basestation
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - common:
        - cd common
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd communication_manager
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - operations:
        - docker:
          - git submodule update --recursive --init operations/deploy/docker
          - cd operations/deploy/docker
          - git clean -d -f -f

      - perception:
        - cd perception
        - git submodule update --recursive --init .
        - git clean -d -f -f
        - cd object_detection
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - subt_launch:
        - cd subt_launch
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - ugv:
        - cd ugv
        - ppc:
          - cd planning-pc/
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - nuc:
          - cd nuc
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - uav:
        - cd uav
        - core:
          - cd core
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - hardware:
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f

    # show the git status in the intermediate-repo
    - pwd
    - git status

  # //////////////////////////////////////////////////////////////////////////////
  - reset:
  # //////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - localhost:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/reset/reset.base
      - +extend: common/git/reset/reset.simulation
      - +extend: common/git/reset/reset.ugv
      - +extend: common/git/reset/reset.uav

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////
      - system76:
        - +extend: common/git/reset/reset.base
        - +extend: common/git/reset/reset.ugv
        - +extend: common/git/reset/reset.ugv.hardware
        - +extend: common/git/reset/reset.uav
        - +extend: common/git/reset/reset.simulation

      - laptop:
        - +extend: common/git/reset/reset.base
        - +extend: common/git/reset/reset.uav
        - +extend: common/git/reset/reset.simulation

    # //////////////////////////////////////////////////////////////////////////
    - slam:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/reset/reset.ugv.slam
      - +extend: common/git/reset/reset.uav.slam

    # prompt git status
    - pwd
    - git status

  # ////////////////////////////////////////////////////////////////////////
  - init:
  # ////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - localhost:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/init/init.base
      - +extend: common/git/init/init.simulation
      - +extend: common/git/init/init.ugv
      - +extend: common/git/init/init.uav

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////
      - system76:
        - +extend: common/git/init/init.base
        - +extend: common/git/init/init.ugv
        - +extend: common/git/init/init.ugv.hardware
        - +extend: common/git/init/init.uav
        - +extend: common/git/init/init.simulation

      - laptop:
        - +extend: common/git/init/init.base
        - +extend: common/git/init/init.uav
        - +extend: common/git/init/init.simulation
    # //////////////////////////////////////////////////////////////////////////
    - slam:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/init/init.ugv.slam
      - +extend: common/git/init/init.uav.slam

  # //////////////////////////////////////////////////////////////////////////////
  - rm:
  # //////////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - localhost:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/rm/rm.base
      - +extend: common/git/rm/rm.simulation
      - +extend: common/git/rm/rm.ugv
      - +extend: common/git/rm/rm.uav

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////
      - system76:
        - +extend: common/git/rm/rm.base
        - +extend: common/git/rm/rm.ugv
        - +extend: common/git/rm/rm.ugv.hardware
        - +extend: common/git/rm/rm.uav
        - +extend: common/git/rm/rm.simulation

      - laptop:
        - +extend: common/git/rm/rm.base
        - +extend: common/git/rm/rm.uav
        - +extend: common/git/rm/rm.simulation

    # //////////////////////////////////////////////////////////////////////////
    - slam:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/rm/rm.ugv.slam
      - +extend: common/git/rm/rm.uav.slam

  # //////////////////////////////////////////////////////////////////////////////
  - branch:
  # //////////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - create:
    # ////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - simulation:
        - cd simulation
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git checkout -b $branch
      - git status

    # //////////////////////////////////////////////////////////////////////////////
    - co:
    # //////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git fetch --all
      - git fetch origin
      - git update-ref refs/heads/$branch origin/$branch
      - git checkout $branch
      - git submodule update --recursive --init .
      - git clean -d -f -f
      - git status

