# //////////////////////////////////////////////////////////////////////////////
# update all the deploy repo git submodules
# //////////////////////////////////////////////////////////////////////////////

- pwd

# //////////////////////////////////////////////////////////////////////////////
- submodule:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - clean:
  # ////////////////////////////////////////////////////////////////////////////
    - common:
      - cd common
    - basestation:
      - cd basestation
    - perception:
      - cd perception
    - subt_launch:
      - cd subt_launch
    - ugv:
      - cd ugv
    - uav:
      - cd uav
    # remove untracked files
    - git clean -xfd
    # remove unstaged changes
    - git checkout -- .
    # remove untracked files in all submodules
    - git submodule foreach --recursive git clean -xfd
    # reset top level
    # - git reset --hard
    # reset the submodules, recursive
    # - git submodule foreach --recursive git reset --hard
    # - git submodule update --init --recursive
    # show the git status
    - git status

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to where the HEAD in the intermediate repo is set to.
  - clone:
  # ////////////////////////////////////////////////////////////////////////
    - extras:
      - uav:
        - git submodule update --init uav
        - cd uav
        - git clean -d -f -f
        - hardware:
          - git submodule update --recursive --init hardware
          - cd hardware
          - git clean -d -f -f
        - slam:
          - git submodule update --recursive --init slam
          - cd slam
          - git clean -d -f -f

      - ugv:
        - git submodule update --init ugv
        - cd ugv
        - git clean -d -f -f
        - slam:
          - devel:
            - git submodule update --recursive --init slam/devel
            - cd slam/devel
            - git clean -d -f -f
          - robot:
            - git submodule update --recursive --init slam/robot
            - cd slam/robot
            - git clean -d -f -f
        - hardware:
          - git submodule update --recursive --init hardware
          - cd hardware/
          - git clean -d -f -f

    - base:
      - basestation:
        - git submodule update --recursive --init basestation
        - cd basestation
        - git clean -d -f -f

      - common:
        - git submodule update --recursive --init common
        - cd common
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
        # git lfs steps
        - cd communication_manager
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - operations:
        - docker:
          - git submodule update --recursive --init operations/deploy/docker
          - cd operations/deploy/docker
          - git clean -d -f -f

      - perception:
        - git submodule update --recursive --init perception
        - cd perception
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
        - cd object_detection
        - git clean -d -f -f

      - simulation:
        - git submodule update --recursive --init simulation
        - cd simulation
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
        - git update-index --assume-unchanged darpa/catkin/.catkin_tools/profiles/profiles.yaml
        # git lfs steps
        - cd subt_gazebo
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - subt_launch:
        - git submodule update --recursive --init subt_launch
        - cd subt_launch
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml

      - uav:
        - git submodule update --init uav
        - cd uav
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
        - core:
          - git submodule update --recursive --init core
          - cd core
          - git clean -d -f -f

      - ugv:
        - git submodule update --init ugv
        - cd ugv
        - git clean -d -f -f
        # ignore the catkin profiles
        - git update-index --assume-unchanged .catkin_tools/profiles/profiles.yaml
        - ppc:
          - git submodule update --recursive --init planning-pc/
          - cd planning-pc/
          - git clean -d -f -f
        - nuc:
          - git submodule update --recursive --init nuc/
          - cd nuc/
          - git clean -d -f -f

    # show the git status in the intermediate-repo
    - git status

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to what the branch in the intermediate repo is set to.
  - pull:
  # ////////////////////////////////////////////////////////////////////////
    - extras:
      - uav:
        - cd uav
        - hardware:
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - slam:
          - cd slam
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - ugv:
        - cd ugv
        - slam:
          - devel:
            - cd slam/devel
            - git submodule update --init --recursive .
            - git clean -d -f -f
          - robot:
            - cd slam/robot
            - git submodule update --init --recursive .
            - git clean -d -f -f

    - base:
      - basestation:
        - cd basestation
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - common:
        - cd common
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd communication_manager
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - operations:
        - docker:
          - git submodule update --recursive --init operations/deploy/docker
          - cd operations/deploy/docker
          - git clean -d -f -f

      - perception:
        - cd perception
        - git submodule update --recursive --init .
        - git clean -d -f -f
        - cd object_detection
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - simulation:
        - cd simulation
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd subt_gazebo
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - subt_launch:
        - cd subt_launch
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - ugv:
        - cd ugv
        - ppc:
          - cd planning-pc/
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - nuc:
          - cd nuc
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - uav:
        - cd uav
        - core:
          - cd core
          - git submodule update --init --recursive .
          - git clean -d -f -f

    # show the git status in the intermediate-repo
    - git status

  # ////////////////////////////////////////////////////////////////////////
  - init:
  # ////////////////////////////////////////////////////////////////////////
    - basestation:
      - git submodule update --init basestation

    - common:
      - git submodule update --init common

    - operations:
      - docker:
        - git submodule update --init operations/deploy/docker

    - perception:
      - git submodule update --init perception

    - simulation:
      - git submodule update --init simulation

    - subt_launch:
      - git submodule update --init subt_launch

    - ugv:
      - git submodule update --init ugv
      - cd ugv
      - ppc:
        - git submodule update --init planning-pc/
      - nuc:
        - git submodule update --init nuc/
      - slam:
        - devel:
          - git submodule update --init slam/devel
        - robot:
          - git submodule update --init slam/robot
      - hardware:
        - git submodule update --init hardware

    - uav:
      - git submodule update --init uav
      - cd uav
      - core:
        - git submodule update --init core
      - hardware:
        - git submodule update --init hardware
      - slam:
        - git submodule update --init slam

  # //////////////////////////////////////////////////////////////////////////////
  - rm:
  # //////////////////////////////////////////////////////////////////////////////
    - extras:
      - uav:
        - cd uav
        - hardware:
          -  git submodule deinit -f hardware
        - slam:
          -  git submodule deinit -f slam
      - ugv:
        - slam:
          - devel:
            - git submodule deinit -f slam/devel
          - robot:
            - git submodule deinit -f slam/robot
        - hardware:
          -  git submodule deinit -f hardware

    - base:
      - basestation:
        - git submodule deinit -f basestation

      - common:
        - git submodule deinit -f common

      - operations:
        - docker:
          - git submodule deinit -f operations/deploy/docker

      - perception:
        -  git submodule deinit -f perception

      - simulation:
        -  git submodule deinit -f simulation

      - subt_launch:
        -  git submodule deinit -f subt_launch

      - uav:
        - cd uav
        - core:
          - git submodule deinit -f core

      - ugv:
        - cd ugv
        - ppc:
          - git submodule deinit -f planning-pc
        - nuc:
          - git submodule deinit -f nuc

  # //////////////////////////////////////////////////////////////////////////////
  - branch:
  # //////////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - create:
    # ////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git checkout -b $branch
      - git status

    # //////////////////////////////////////////////////////////////////////////////
    - co:
    # //////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git fetch --all
      - git fetch origin
      - git update-ref refs/heads/$branch origin/$branch
      - git checkout $branch
      - git submodule update --recursive --init .
      - git clean -d -f -f
      - git status

