# //////////////////////////////////////////////////////////////////////////////
# update all the deploy repo git submodules
# //////////////////////////////////////////////////////////////////////////////

- pwd

# //////////////////////////////////////////////////////////////////////////////
- submodule:
# //////////////////////////////////////////////////////////////////////////////

  # ////////////////////////////////////////////////////////////////////////////
  - clean:
  # ////////////////////////////////////////////////////////////////////////////
    - common:
      - cd common
    - basestation:
      - cd basestation
    - perception:
      - cd perception
    - simulation:
      - cd simulation
    - subt_launch:
      - cd subt_launch
    - ugv:
      - cd ugv
    - uav:
      - cd uav
    # remove untracked files
    - git clean -xfd
    # remove unstaged changes
    - git checkout -- .
    # remove untracked files in all submodules
    - git submodule foreach --recursive git clean -xfd
    # reset top level
    # - git reset --hard
    # reset the submodules, recursive
    # - git submodule foreach --recursive git reset --hard
    # - git submodule update --init --recursive
    # show the git status
    - pwd
    - git status

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to where the HEAD in the intermediate repo is set to.
  - clone:
  # ////////////////////////////////////////////////////////////////////////

    # //////////////////////////////////////////////////////////////////////////
    - localhost:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/clone/clone.base
      - +extend: common/git/clone/clone.simulation
      - +extend: common/git/clone/clone.ugv
      - +extend: common/git/clone/clone.uav

    # //////////////////////////////////////////////////////////////////////////
    - basestation:
    # //////////////////////////////////////////////////////////////////////////
      - system76:
        - +extend: common/git/clone/clone.base
        - +extend: common/git/clone/clone.ugv
        - +extend: common/git/clone/clone.ugv.hardware
        - +extend: common/git/clone/clone.uav
        - +extend: common/git/clone/clone.simulation

      - laptop.uav:
        - +extend: common/git/clone/clone.base
        - +extend: common/git/clone/clone.uav
        - +extend: common/git/clone/clone.simulation

    # //////////////////////////////////////////////////////////////////////////
    - slam:
    # //////////////////////////////////////////////////////////////////////////
      - +extend: common/git/clone/clone.ugv.slam
      - +extend: common/git/clone/clone.uav.slam

    # show the git status in the intermediate-repo
    - pwd
    - git status

  # ////////////////////////////////////////////////////////////////////////
  # clones the submodules to what the branch in the intermediate repo is set to.
  - pull:
  # ////////////////////////////////////////////////////////////////////////
    - extras:
      - simulation:
        - cd simulation
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd subt_gazebo
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - uav:
        - cd uav
        - slam:
          - cd slam
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - ugv:
        - cd ugv
        - hardware:
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - slam:
          - devel:
            - cd slam/devel
            - git submodule update --init --recursive .
            - git clean -d -f -f
          - robot:
            - cd slam/robot
            - git submodule update --init --recursive .
            - git clean -d -f -f

    - base:
      - basestation:
        - cd basestation
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - common:
        - cd common
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd communication_manager
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - operations:
        - docker:
          - git submodule update --recursive --init operations/deploy/docker
          - cd operations/deploy/docker
          - git clean -d -f -f

      - perception:
        - cd perception
        - git submodule update --recursive --init .
        - git clean -d -f -f
        - cd object_detection
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - subt_launch:
        - cd subt_launch
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - ugv:
        - cd ugv
        - ppc:
          - cd planning-pc/
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - nuc:
          - cd nuc
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - uav:
        - cd uav
        - core:
          - cd core
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - hardware:
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f

    # show the git status in the intermediate-repo
    - pwd
    - git status

  # //////////////////////////////////////////////////////////////////////////////
  - reset:
  # //////////////////////////////////////////////////////////////////////////////
    - extras:
      - simulation:
        # remove
        - git submodule deinit -f simulation
        # re-clone
        - cd simulation
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd subt_gazebo
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - uav:
        - cd uav
        - slam:
          # remove
          - git submodule deinit -f slam
          # re-clone
          - cd slam
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - ugv:
        - cd ugv
        - slam:
          - devel:
            # reset
            - git submodule deinit -f slam/devel
            # re-clone
            - cd slam/devel
            - git submodule update --init --recursive .
            - git clean -d -f -f
          - robot:
            # reset
            - git submodule deinit -f slam/robot
            # re-clone
            - cd slam/robot
            - git submodule update --init --recursive .
            - git clean -d -f -f
        - hardware:
          # remove
          - git submodule deinit -f hardware
          # re-clone
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f

    - base:
      - basestation:
        # remove
        - git submodule deinit -f basestation
        # re-clone
        - cd basestation
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - common:
        # remove
        - git submodule deinit -f common
        # re-clone
        - cd common
        - git submodule update --recursive --init .
        - git clean -d -f -f
        # git lfs steps
        - cd communication_manager
        - git lfs fetch
        - git lfs pull
        - git lfs install

      - operations:
        - docker:
          # remove
          - git submodule deinit -f operations/deploy/docker
          # re-clone
          - git submodule update --recursive --init operations/deploy/docker
          - cd operations/deploy/docker
          - git clean -d -f -f

      - perception:
        # remove
        - git submodule deinit -f perception
        # re-clone
        - cd perception
        - git submodule update --recursive --init .
        - git clean -d -f -f
        - cd object_detection
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - subt_launch:
        # remove
        - git submodule deinit -f subt_launch
        # re-clone
        - cd subt_launch
        - git submodule update --recursive --init .
        - git clean -d -f -f

      - ugv:
        - cd ugv
        - ppc:
          # remove
          - git submodule deinit -f planning-pc
          # re-clone
          - cd planning-pc/
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - nuc:
          # remove
          - git submodule deinit -f nuc
          # re-clone
          - cd nuc
          - git submodule update --init --recursive .
          - git clean -d -f -f

      - uav:
        - cd uav
        - core:
          # remove
          - git submodule deinit -f core
          # re-clone
          - cd core
          - git submodule update --init --recursive .
          - git clean -d -f -f
        - hardware:
          # remove
          - git submodule deinit -f hardware
          # re-clone
          - cd hardware
          - git submodule update --init --recursive .
          - git clean -d -f -f

    # prompt git status
    - pwd
    - git status

  # ////////////////////////////////////////////////////////////////////////
  - init:
  # ////////////////////////////////////////////////////////////////////////
    - extras:
      - simulation:
        - git submodule update --init simulation
      - ugv:
        - git submodule update --init ugv
        - cd ugv
        - slam:
          - devel:
            - git submodule update --init slam/devel
          - robot:
            - git submodule update --init slam/robot
        - hardware:
          - git submodule update --init hardware
      - uav:
        - git submodule update --init uav
        - cd uav
        - slam:
          - git submodule update --init slam

    - base:
      - basestation:
        - git submodule update --init basestation

      - common:
        - git submodule update --init common

      - operations:
        - docker:
          - git submodule update --init operations/deploy/docker

      - perception:
        - git submodule update --init perception

      - subt_launch:
        - git submodule update --init subt_launch

      - ugv:
        - git submodule update --init ugv
        - cd ugv
        - ppc:
          - git submodule update --init planning-pc/
        - nuc:
          - git submodule update --init nuc/

      - uav:
        - git submodule update --init uav
        - cd uav
        - core:
          - git submodule update --init core
        - hardware:
          - git submodule update --init hardware

  # //////////////////////////////////////////////////////////////////////////////
  - rm:
  # //////////////////////////////////////////////////////////////////////////////
    - extras:
      - simulation:
        -  git submodule deinit -f simulation
      - uav:
        - cd uav
        - slam:
          -  git submodule deinit -f slam
      - ugv:
        - cd ugv
        - slam:
          - devel:
            - git submodule deinit -f slam/devel
          - robot:
            - git submodule deinit -f slam/robot
        - hardware:
          -  git submodule deinit -f hardware

    - base:
      - basestation:
        - git submodule deinit -f basestation

      - common:
        - git submodule deinit -f common

      - operations:
        - docker:
          - git submodule deinit -f operations/deploy/docker

      - perception:
        -  git submodule deinit -f perception

      - subt_launch:
        -  git submodule deinit -f subt_launch

      - uav:
        - cd uav
        - core:
          - git submodule deinit -f core
        - hardware:
          -  git submodule deinit -f hardware

      - ugv:
        - cd ugv
        - ppc:
          - git submodule deinit -f planning-pc
        - nuc:
          - git submodule deinit -f nuc

  # //////////////////////////////////////////////////////////////////////////////
  - branch:
  # //////////////////////////////////////////////////////////////////////////////

    # ////////////////////////////////////////////////////////////////////////////
    - create:
    # ////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - simulation:
        - cd simulation
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git checkout -b $branch
      - git status

    # //////////////////////////////////////////////////////////////////////////////
    - co:
    # //////////////////////////////////////////////////////////////////////////////
      - common:
        - cd common
      - basestation:
        - cd basestation
      - perception:
        - cd perception
      - subt_launch:
        - cd subt_launch
      - ugv:
        - cd ugv
      - uav:
        - cd uav
      # checkout to the specified branch & update submodules
      - git fetch --all
      - git fetch origin
      - git update-ref refs/heads/$branch origin/$branch
      - git checkout $branch
      - git submodule update --recursive --init .
      - git clean -d -f -f
      - git status

