blacklist:
  - gazebo_interface
build_space: ../../build/ugv/simulation/
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/ugv/simulation/
extend_path: ../../devel/ugv/simulation/darpa
install: false
install_space: ../../install/ugv/simulation/
isolate_install: false
jobs_args: []
log_space: ../../logs/ugv/simulation/
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
